- pythran/pythonic/types/numpy_fexpr.hpp
- pythran/tests/test_ndarray.py
> Allow masking a numpy mask

- pythran/pythonic/types/ndarray.hpp
numpy's ndarray use ssize_t to store their shape, while Pythran uses
long, for compatibility with other Python integer. This does not cause
any issue on 64 bit platform, but it was problematic under 32 bit
platform where sizeof(long) != sizeof(ssize_t).
this patch proposes a non-intrusive fix.
> 32bit compatibility for ndarray

- pythran/__init__.py
- pythran/analyses/constant_expressions.py
- pythran/analyses/lazyness_analysis.py
- pythran/analyses/potential_iterator.py
- pythran/analyses/use_def_chain.py
- pythran/backend.py
- pythran/cxxtypes.py
- pythran/optimizations/dead_code_elimination.py
- pythran/spec.py
- pythran/toolchain.py
- pythran/types/types.py
- pythran/unparse.py
* forbid var = lambda ... pattern
* nothing before top-level import
> PEP8 upgrade

- pythran/pythonic/__builtin__/str/join.hpp
- pythran/toolchain.py
- pythran/transformations/handle_import.py
- scripts/pythran
> Add pwd in search paths

- pythran/pythonic/__builtin__/str/join.hpp
- pythran/pythonic/numpy/float32.hpp
- pythran/pythonic/numpy/float64.hpp
- pythran/pythonic/numpy/int16.hpp
- pythran/pythonic/numpy/int32.hpp
- pythran/pythonic/numpy/int64.hpp
- pythran/pythonic/numpy/int8.hpp
- pythran/pythonic/numpy/uint16.hpp
- pythran/pythonic/numpy/uint32.hpp
- pythran/pythonic/numpy/uint64.hpp
- pythran/pythonic/numpy/uint8.hpp
- pythran/pythonic/types/numpy_op_helper.hpp
- pythran/pythonic/types/vectorizable_type.hpp
- pythran/pythonic/utils/meta.hpp
- pythran/tests/test_env.py
- pythran/tests/test_numpy_ufunc_unary.py
> Allow nexpr version of float/int numpy conversion

- Changelog
- pythran/__init__.py
> Pythran 0.7 - PyData Paris

- scripts/pythran
Credits go to Marc Gailhanou for the bug report!
> Fix pythran -L option parsing

- README.rst
- setup.py
- do not rely on git to fetch nt2
- do not rely on make to build nt2
> Make setup.py more portable

- doc/MANUAL.rst
> pythran: change 'l0', 'l1' to 'arr0', 'arr1'

- pythran/pythonic/include/itertools/combinations.hpp
- pythran/pythonic/include/itertools/count.hpp
- pythran/pythonic/include/itertools/ifilter.hpp
- pythran/pythonic/include/itertools/imap.hpp
- pythran/pythonic/include/itertools/product.hpp
- pythran/pythonic/include/types/generator.hpp
- pythran/pythonic/include/utils/iterator.hpp
- pythran/pythonic/itertools/combinations.hpp
- pythran/pythonic/itertools/count.hpp
- pythran/pythonic/itertools/ifilter.hpp
- pythran/pythonic/itertools/imap.hpp
- pythran/pythonic/itertools/product.hpp
- pythran/pythonic/types/generator.hpp
- pythran/pythonic/utils/iterator.hpp
Travis is almost happy (only formating failed, I will update it only if everything else is right to avoid extra travis validation)
> Itertools refactor

- .travis.yml
- pythran/pythonic/include/numpy/random/binomial.hpp
- pythran/pythonic/include/numpy/random/generator.hpp
- pythran/pythonic/include/numpy/random/random.hpp
- pythran/pythonic/numpy/random/binomial.hpp
- pythran/tables.py
- pythran/tests/test_numpy_random.py
> Changing numpy random generator & adding numpy.random.binomial

- doc/CLI.rst
- doc/MANUAL.rst
- pythran/toolchain.py
It holds some compilation informations
> Add __pythran__ global variable

- README.rst
- doc/INTERNAL.rst
- pythran/backend.py
- pythran/cxxgen.py
- pythran/frontend.py
- pythran/tests/test_env.py
- pythran/toolchain.py
- pythran/transformations/__init__.py
- pythran/transformations/extract_doc_strings.py
Generate proper __doc__ member for module and functions
> Keep docstring information in native version

- pythran/pythonic/include/types/tuple.hpp
- pythran/pythonic/types/tuple.hpp
- pythran/tests/test_base.py
the error lied in a bad namespace declaration, this fixes Issue #473.
> Fix stream operator for std::tuple

- pythran/pythonic/include/numpy/all.hpp
- pythran/pythonic/include/numpy/any.hpp
- pythran/pythonic/include/numpy/reduce.hpp
- pythran/pythonic/numpy/all.hpp
- pythran/pythonic/numpy/any.hpp
- pythran/pythonic/numpy/reduce.hpp
- pythran/tests/test_numpy_func1.py
- pythran/tests/test_numpy_func2.py
> Fix bug in some numpy functions when passed scalar argument

- README.rst
> Update README.rst style

- setup.py
Warn about missing setuptools during setup, see #489
> Explicit setuptools dependency

- doc/MANUAL.rst
- pythran/spec.py
- pythran/tests/test_spec_parser.py
This makes it possible, in case of very long signature, to still follow
pep8 recommendation.
> Support multiline pythran spec

- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/include/types/numpy_texpr.hpp
- pythran/pythonic/types/ndarray.hpp
- pythran/pythonic/types/numpy_texpr.hpp
- pythran/tests/cases/value_index.py
- pythran/tests/test_ndarray.py
* It is not a positional support with multiple dim access.
> Add support for ndarray indexing with long for N dim.

- doc/MANUAL.rst
> Review of the documentation by ``Ron``

- doc/MANUAL.rst
- pythran/__init__.py
- pythran/magic.py
- pythran/pythonic/include/__builtin__/reduce.hpp
- pythran/pythonic/include/__builtin__/sum.hpp
The following sequence now works:
%import pythran
%load_ext pythran.magic
%%pythran -O3 -fopenmp
#pythran export foo(in)
def foo(n):
...
> Better integration with jupyter/ipython

- .travis.yml
- pythran/pythonic/include/numpy/abs.hpp
- pythran/pythonic/numpy/abs.hpp
NT2's is more accurate but soooo slow on complex
> Use std::abs for scalar version and not nt2's

- pythran/transformations/handle_import.py
* It was looking for builtin modules based on alias name which is incorrect.
> Fix import warning.

- pythran/pythonic/include/numpy/random/generator.hpp
* instead of using default seed
Fix #567
> Make random really random

- setup.py
* a+ replace content but smaller content will keep garbage at the end
without manual truncate
> Fix config file without GMP support.

- doc/MANUAL.rst
Original issue reported by @nils-werner
> Fix documentation and tests on setup.py integration

- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/include/types/raw_array.hpp
- pythran/pythonic/include/utils/shared_ref.hpp
- pythran/pythonic/types/ndarray.hpp
- pythran/pythonic/types/raw_array.hpp
- pythran/pythonic/utils/shared_ref.hpp
For the record, @joker-eph spotted this with a FIXME +1 year ago...
> Fix subtle memory leak in ndarray management

- pythran/conversion.py
* Still part of the last numpy update fix.
Fix #619
> Fix use of NoValue Attribut from numpy.

- pythran/cxxtypes.py
- pythran/optimizations/loop_full_unrolling.py
- pythran/tests/cases/matmul.py
> Fix invalid test parameters

- pythran/config.py
> Fix blas setting in .pythranrc

- pythran/pythonic/numpy/dot.hpp
- pythran/tests/test_numpy_func3.py
> Fix dot operation on regular shape

- README.rst
> Update install requirements

- doc/MANUAL.rst
- pythran/spec.py
- pythran/tests/cases/fannkuch.py
- pythran/tests/cases/fannkuch.pythran
- pythran/toolchain.py
Makes it possible to put export lines in a third-party file.
> Introduce .pythran file

- pythran/pythonic/include/types/list.hpp
- pythran/pythonic/types/list.hpp
> Use emplace_back instead of push_back in list

- pythran/pythonic/__builtin__/xrange.hpp
- pythran/pythonic/include/__builtin__/xrange.hpp
Everything can be done through xrange_iterator
> Remove useless xrange_riterator

- pythran/pythonic/utils/broadcast_copy.hpp
A useless div was creating huge slowdown in some cases.
Fix #254
> Improve broadcast_copy performance

- pythran/pythonic/__builtin__/max.hpp
- pythran/pythonic/__builtin__/min.hpp
- pythran/pythonic/__builtin__/minmax.hpp
- pythran/pythonic/include/__builtin__/max.hpp
- pythran/pythonic/include/__builtin__/min.hpp
- pythran/pythonic/include/__builtin__/minmax.hpp
> Syndicate min/max code into a parametric minmax function

- AUTHORS
> Fix typo in AUTHORS

- pythran/tables.py
- pythran/tests/test_numpy_func2.py
Now support dtype named argument.
> Improve signature of numpy.array

- pythran/__init__.py
- pythran/analyses/constant_expressions.py
- pythran/analyses/dependencies.py
- pythran/conversion.py
- pythran/interval.py
- pythran/optimizations/inline_builtins.py
- pythran/spec.py
- pythran/tests/test_typing.py
- pythran/toolchain.py
This makes correct compilation much faster, without giving up with
typing error.
> Delay typing until an error is found

- setup.py
> setup.py: Numpy as an extra dependency. Change raise to warn if numpy

- pythran/pythonic/types/generator.hpp
- pythran/pythonic/types/long.hpp
- pythran/pythonic/types/slice.hpp
- pythran/tests/test_file.py
- pythran/tests/test_numpy_random.py
This include a file that was only included in debug mode, and debug mode
is never tested...
> Remove obsolete reference to nt2 files

- pythran/pythonic/include/numpy/cumsum.hpp
- pythran/pythonic/numpy/cumsum.hpp
> Incorrect cumsum operation

- .travis.yml
- pythran/pythonic/include/scipy/special/gamma.hpp
- pythran/pythonic/include/scipy/special/gammaln.hpp
- pythran/pythonic/scipy/special/gamma.hpp
- pythran/pythonic/scipy/special/gammaln.hpp
- pythran/tables.py
- pythran/tests/test_numpy_ufunc_unary.py
Hi,
This pull request adds gamma and gammaln functions from scipy.special with boost simd versions.
> Add scipy.special.{gamma gammaln}

- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/include/types/raw_array.hpp
- pythran/pythonic/types/ndarray.hpp
- pythran/pythonic/types/raw_array.hpp
- pythran/pythonic/types/tuple.hpp
PyTuple_New does *not* steal references.
Fix #720
> Fix leak when creating tuple

- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/types/ndarray.hpp
- pythran/tests/cases/diffusion_numpy.py
- pythran/tests/cython/setup_diffuse.py
better to_python/from_python signatures
> Improved cython support

- pythran/magic.py
- pythran/tests/ipython_script_timeit.ipy
- pythran/tests/test_ipython.py
- Update function even if options changed
- Code cleaning
- Tests
> Improve jupyter magic

- pythran/optimizations/__init__.py
- pythran/optimizations/constant_folding.py
- pythran/optimizations/list_to_tuple.py
- pythran/pythonic/include/types/list.hpp
- pythran/pythonic/types/list.hpp
- pythran/pythran.cfg
- pythran/tests/test_numpy_func1.py
Turning list to tuple whenever possible does help. This is till very
naive but should handle most cases.
> Add support for numpy.ones([...])

- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/include/types/numpy_expr.hpp
- pythran/pythonic/include/types/numpy_fexpr.hpp
- pythran/pythonic/include/types/numpy_gexpr.hpp
- pythran/pythonic/include/types/numpy_iexpr.hpp
- pythran/pythonic/include/types/numpy_texpr.hpp
- pythran/tests/test_doc.py
NFC, but workaround a g++ bug (see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82311)
> Reorder numpy_*expr declaration

- pythran/spec.py
- pythran/tests/notebooks/export.ipynb
And validate that using a dedicated notebook!
> Remove shift/reduce conflicts in Pythran grammar

- pythran/pythonic/include/types/numpy_expr.hpp
- pythran/pythonic/numpy/any.hpp
- pythran/tests/test_numpy_func2.py
Fixes #755, thanks to Yann Diorcet <yann.diorcet@xenocs.com> for the bug
report and the test cases.
> Fix incorrect numpy_expr iterator comparison

- pythran/pythonic/include/types/numpy_gexpr.hpp
- pythran/pythonic/types/numpy_gexpr.hpp
- pythran/tests/cases/weights.py
> Fix incorrect handling of complex generalized expression

- pythran/pythonic/types/complex.hpp
- pythran/pythonic/types/float.hpp
- pythran/tests/test_typing.py
Same for complex <> np.complex128 and int <> np.int64
Fix #785
> Accept both np.float64 and float for float sepcification

- pythran/pythran-darwin.cfg
> Ship a non-verbose config file for OSX

- pythran/cxxgen.py
- pythran/pythonic/python/core.hpp
> Pretty-print argument type upon type mismatch

- pythran/pythonic/include/types/list.hpp
- pythran/pythonic/types/list.hpp
- pythran/tests/test_list.py
> Correct type inference when combining two lists

- setup.py
> Correct support of develop target for setup.py

- pythran/pythonic/include/types/numpy_gexpr.hpp
- pythran/pythonic/types/numpy_gexpr.hpp
- pythran/tests/cases/compute_subpix_2d_gaussian2.py
> Handle fast indexing of gexpr through tuple of indices

- pythran/analyses/dependencies.py
- pythran/backend.py
- pythran/pythonic/include/operator_/icommon.hpp
- pythran/pythonic/include/operator_/ifloordiv.hpp
- pythran/pythonic/include/operator_/imatmul.hpp
- pythran/pythonic/include/operator_/imod.hpp
- pythran/pythonic/include/operator_/ipow.hpp
- pythran/pythonic/include/operator_/itruediv.hpp
- pythran/pythonic/operator_/icommon.hpp
- pythran/pythonic/operator_/ifloordiv.hpp
- pythran/pythonic/operator_/imatmul.hpp
- pythran/pythonic/operator_/imod.hpp
- pythran/pythonic/operator_/ipow.hpp
- pythran/pythonic/operator_/itruediv.hpp
- pythran/tables.py
- pythran/tests/test_ndarray.py
> Fix augmented assign behavior on arrays

- pythran/pythonic/include/types/numpy_vexpr.hpp
- pythran/pythonic/types/numpy_vexpr.hpp
> Better support for array indexing by an other array

- pythran/conversion.py
- pythran/tables.py
- pythran/tests/test_numpy_func0.py
- pythran/transformations/remove_named_arguments.py
> Fix bugs in automatic keyword handling

- pythran/pythonic/include/numpy/bincount.hpp
- pythran/pythonic/numpy/bincount.hpp
- pythran/tests/test_numpy_func2.py
> Allow numpy.bincount to receive any numpy expression

- pythran/pythonic/numpy/dot.hpp
I think that you just forgot to close a curly bracket.
> [NUMPY] Tiny #defined bugfix.

- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/include/types/numpy_broadcast.hpp
- pythran/pythonic/include/types/numpy_expr.hpp
- pythran/pythonic/include/types/numpy_gexpr.hpp
- pythran/pythonic/include/types/numpy_iexpr.hpp
- pythran/pythonic/include/types/numpy_texpr.hpp
- pythran/pythonic/types/ndarray.hpp
- pythran/pythonic/types/numpy_broadcast.hpp
- pythran/pythonic/types/numpy_expr.hpp
- pythran/pythonic/types/numpy_gexpr.hpp
- pythran/pythonic/types/numpy_iexpr.hpp
- pythran/pythonic/types/numpy_texpr.hpp
- pythran/tests/test_ndarray.py
> ndarray.bool implementation

- pythran/pythonic/include/types/numpy_texpr.hpp
- pythran/tests/cases/lapl2d.py
Thanks to Thierry Dumont for reporting the issue!
> Fx transposed array assignment

- pythran/tests/openmp.legacy/omp_parallel_num_threads.py
- pythran/tests/openmp.legacy/omp_task_final.py
Resolves undefined names in legacy tests
> import unittest

- pythran/tests/test_numpy_func2.py
- pythran/transformations/remove_named_arguments.py
> Support default argument for numpy.arange

- pythran/tables.py
- pythran/tests/test_numpy_linalg.py
> Support numpy.Inf

- pythran/conversion.py
- pythran/pythonic/include/types/list.hpp
- pythran/tests/test_list.py
> Provide minimal array interface for empty_list

- pythran/pythonic/include/functools/partial.hpp
- pythran/pythonic/include/types/variant_functor.hpp
- pythran/pythonic/types/variant_functor.hpp
- pythran/tests/test_typing.py
Thanks to Yann Diorcet for spotting the bug!
> Fix incorrect memory handling in variant functor

- pythran/pythonic/include/types/numpy_expr.hpp
> numpy_expr: Fix initilization order

- pythran/config.py
This can causse issue with setup.py --fullname
> Avoid numpy polution of stdout

- pythran/analyses/__init__.py
- pythran/analyses/argument_effects.py
- pythran/analyses/argument_read_once.py
- pythran/analyses/has_return.py
- pythran/analyses/static_expressions.py
- pythran/middlend.py
- pythran/pythonic/__builtin__/pythran/StaticIfReturn.hpp
- pythran/pythonic/__builtin__/pythran/is_none.hpp
- pythran/pythonic/__builtin__/pythran/static_if_.hpp
- pythran/pythonic/include/__builtin__/pythran/StaticIfReturn.hpp
- pythran/pythonic/include/__builtin__/pythran/is_none.hpp
- pythran/pythonic/include/__builtin__/pythran/static_if_.hpp
- pythran/pythonic/include/types/combined.hpp
- pythran/tables.py
- pythran/tests/test_none.py
- pythran/transformations/__init__.py
- pythran/transformations/normalize_compare.py
- pythran/transformations/normalize_is_none.py
- pythran/transformations/normalize_static_if.py
- pythran/unparse.py
This means you can write somewhat polymorphic code as long as
it's guarded by ``is None`` constructs.
Implemented using an analysis static_expressions, and two normalizing
transformations, namely normalize_is_none and normalize_static_if
> Decent support for static-if like constructs

- pythran/tests/test_typing.py
- pythran/types/types.py
> Remove legacy typing code

- pythran/pythonic/__builtin__/pythran/StaticIfNoReturn.hpp
- pythran/pythonic/__builtin__/pythran/StaticIfReturn.hpp
- pythran/pythonic/__builtin__/pythran/static_if_.hpp
- pythran/pythonic/include/__builtin__/pythran/StaticIfNoReturn.hpp
- pythran/pythonic/include/__builtin__/pythran/StaticIfReturn.hpp
- pythran/pythonic/include/__builtin__/pythran/static_if_.hpp
- pythran/pythonic/include/types/static_if.hpp
- pythran/pythonic/types/static_if.hpp
- pythran/tables.py
- pythran/tests/test_none.py
- pythran/transformations/normalize_static_if.py
Prepare the way for isinstance :-)
> Cleaner and easier to maintain engine for static-if

- pythran/pythonic/include/types/numpy_texpr.hpp
- pythran/pythonic/types/ndarray.hpp
- pythran/pythonic/types/numpy_texpr.hpp
- pythran/tests/test_ndarray.py
Should fix #960 , @diorcety can you confirm?
> Fix taking a view of a transposed expression

- pythran/pythonic/include/types/tuple.hpp
- pythran/tests/cases/_histogram.py
Thanks @diorcety for the bug report!
> Fix pshape eq neq operator

- pythran/pythonic/include/numpy/array.hpp
- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/numpy/array.hpp
- pythran/pythonic/types/ndarray.hpp
- pythran/tests/test_ndarray.py
> Fix building array from pshape

- pythran/pythonic/include/types/numpy_texpr.hpp
- pythran/pythonic/types/numpy_texpr.hpp
- pythran/tests/test_ndarray.py
The implementation is not very good, but it should work...
> Fix masking of transposed expression in dimension > 1

- pythran/dist.py
The current implementation run multiple times the transpilation (for example sdist then for build and for install)
This one do that in simpliest way
> Improve pythran dist

- pythran/pythonic/include/types/NoneType.hpp
> Fix NoneType friends

- pythran/pythonic/__builtin__/bool_.hpp
- pythran/pythonic/__builtin__/float_.hpp
- pythran/pythonic/__builtin__/int_.hpp
- pythran/pythonic/include/types/str.hpp
- pythran/pythonic/numpy/float32.hpp
- pythran/pythonic/numpy/float64.hpp
- pythran/pythonic/types/str.hpp
- pythran/tests/test_advanced.py
- pythran/tests/test_str.py
> Improve type conversions from str

- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/include/types/numpy_expr.hpp
- pythran/pythonic/include/types/numpy_iexpr.hpp
- pythran/pythonic/include/types/numpy_texpr.hpp
- pythran/pythonic/include/types/numpy_vexpr.hpp
- pythran/pythonic/include/utils/numpy_traits.hpp
- pythran/pythonic/types/ndarray.hpp
- pythran/pythonic/types/numpy_expr.hpp
- pythran/pythonic/types/numpy_texpr.hpp
- pythran/pythonic/types/numpy_vexpr.hpp
- pythran/tests/test_ndarray.py
> Correct typing of mask/index array indexing

- pythran/pythonic/python/core.hpp
- pythran/pythonic/types/ndarray.hpp
> Conversion: Handle gexpr of texpr, and better error report

- pythran/pythonic/include/types/list.hpp
- pythran/pythonic/include/types/numpy_gexpr.hpp
- pythran/pythonic/include/types/numpy_op_helper.hpp
- pythran/pythonic/include/types/tuple.hpp
- pythran/pythonic/types/exceptions.hpp
- pythran/pythonic/types/list.hpp
- pythran/pythonic/types/numpy_gexpr.hpp
- pythran/pythonic/types/numpy_iexpr.hpp
- pythran/pythonic/types/tuple.hpp
- pythran/tests/test_advanced.py
missing gexpr definition, reorder include mess to avoid including
ndarray as a side effect.
> Fix slicing of array

- pythran/pythonic/include/numpy/square.hpp
- pythran/pythonic/include/types/numpy_broadcast.hpp
- pythran/tests/test_ndarray.py
Leads to significant performance improvement, and fixes #807
> Fix promotion of scalar to complex during expr evaluation

- pythran/tables.py
> Add except AttributeError when checking omp.VERSION

- pythran/pythonic/include/types/numpy_expr.hpp
- pythran/tests/test_ndarray.py
> Fix combined of texpr and expr

- docs/MANUAL.rst
- pythran/dist.py
- pythran/pythran-darwin.cfg
- pythran/pythran-linux.cfg
- pythran/pythran-linux2.cfg
- pythran/pythran-win32.cfg
> Add the ignoreflags setting to skip some compiler flags

- pythran/pythonic/include/numpy/remainder.hpp
- pythran/pythonic/numpy/remainder.hpp
- pythran/tests/test_numpy_func1.py
numpy.remainder is different from std::remainder
> Fix remainder implementation

- pythran/pythonic/include/types/numpy_expr.hpp
- pythran/pythonic/types/numpy_expr.hpp
- pythran/tests/test_ndarray.py
> Fix numpy expr extended slicing

- pythran/backend.py
- pythran/cxxtypes.py
- pythran/pythonic/include/__builtin__/getattr.hpp
- pythran/pythonic/include/numpy/imag.hpp
- pythran/pythonic/include/numpy/ndim.hpp
- pythran/pythonic/include/numpy/real.hpp
- pythran/pythonic/include/types/attr.hpp
- pythran/pythonic/include/types/complex.hpp
- pythran/pythonic/include/types/exceptions.hpp
- pythran/pythonic/include/types/file.hpp
- pythran/pythonic/include/types/finfo.hpp
- pythran/pythonic/include/types/int.hpp
- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/include/types/slice.hpp
- pythran/pythonic/numpy/complex64.hpp
- pythran/pythonic/numpy/imag.hpp
- pythran/pythonic/numpy/ndim.hpp
- pythran/pythonic/numpy/real.hpp
- pythran/pythonic/types/complex.hpp
- pythran/pythonic/types/exceptions.hpp
- pythran/pythonic/types/file.hpp
- pythran/pythonic/types/finfo.hpp
- pythran/pythonic/types/int.hpp
- pythran/pythonic/types/ndarray.hpp
- pythran/tests/test_ndarray.py
> Rework getattr subsystem to be more easily extendible

- pythran/pythonic/include/numpy/broadcast_to.hpp
- pythran/pythonic/numpy/broadcast_to.hpp
- pythran/tables.py
- pythran/tests/test_numpy_func0.py
Reusing existing broadcasting engine works like a charm!
> Support np.broadcast_to

- pythran/optimizations/constant_folding.py
- pythran/optimizations/forward_substitution.py
- pythran/tests/test_numpy_random.py
Constant-fold and forward substitute them in simple cases
This fixes #1143
> Better optimize indexing of slices

- pythran/pythonic/include/__builtin__/pythran/abssqr.hpp
- pythran/pythonic/numpy/argminmax.hpp
- pythran/pythonic/types/vectorizable_type.hpp
This is a WIP, so size constraints need to be verified.
> Improve simd performance of argminmax algorithm

- pythran/pythonic/types/ndarray.hpp
- pythran/tests/test_complex.py
With extra test cases.
This should fix #1134.
> Fix real/imag part of a numpy_expr

- pythran/pythonic/include/numpy/transpose.hpp
- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/include/types/nditerator.hpp
- pythran/pythonic/include/types/numpy_texpr.hpp
- pythran/pythonic/numpy/transpose.hpp
- pythran/pythonic/types/ndarray.hpp
- pythran/pythonic/types/numpy_gexpr.hpp
- pythran/pythonic/types/numpy_texpr.hpp
- pythran/tests/test_ndarray.py
> Correct support of assignment of a transposed view through a slice

- pythran/tests/test_numpy_func2.py
> Tuple-to-std-array conversion is now widely handled

- pythran/pythonic/include/types/numpy_gexpr.hpp
- pythran/tests/test_numpy_func2.py
> Allow reshaping of an extended slice

- pythran/pythonic/include/types/tuple.hpp
- pythran/tests/test_none.py
> Fix array combiner

- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/include/types/numpy_broadcast.hpp
- pythran/pythonic/include/types/numpy_op_helper.hpp
- pythran/pythonic/include/types/tuple.hpp
- pythran/pythonic/numpy/rollaxis.hpp
- pythran/pythonic/types/numpy_broadcast.hpp
- pythran/pythonic/types/str.hpp
- pythran/tests/test_numpy_broadcasting.py
- pythran/tests/test_numpy_func0.py
- pythran/tests/test_str.py
It's now possible to slice, index, etc expression involving broadcasting.
Fix #1163
> Rework and improve expression broadcasting support

- pythran/pythonic/include/numpy/transpose.hpp
- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/include/types/numpy_texpr.hpp
- pythran/pythonic/numpy/transpose.hpp
- pythran/pythonic/types/ndarray.hpp
- pythran/pythonic/types/numpy_texpr.hpp
- pythran/tests/cases/pythagorean_triples.py
- pythran/tests/test_ndarray.py
This fixes commit 8b4f22aa0ef0a33308d87b2dcb7d9b4cef3a6187.
> Fix "Correct support of assignment of a transposed view through a slice"

- pythran/pythonic/include/types/NoneType.hpp
- pythran/pythonic/types/NoneType.hpp
- pythran/tests/test_none.py
> Support tuple with NoneType

- pythran/pythonic/types/NoneType.hpp
> Fix invalid lifetime during cast

- pythran/pythonic/types/str.hpp
- pythran/tests/test_str.py
> Fix str assign behaviour from a str slice

- pythran/pythonic/include/numpy/interp.hpp
- pythran/pythonic/numpy/interp.hpp
- pythran/pythonic/numpy/interp_core.cpp
- pythran/tables.py
- pythran/tests/test_numpy_func3.py
Re-opening this after cleanup of merge and so on.
> Implement interp

- pythran/pythonic/include/types/NoneType.hpp
- pythran/pythonic/operator_/ifloordiv.hpp
- pythran/pythonic/types/NoneType.hpp
- pythran/tests/test_none.py
> Support more operator on none types

- pythran/pythonic/python/core.hpp
> PrettyPrint advertised capsule type when reporting type mismatch

- pythran/pythonic/include/numpy/append.hpp
- pythran/pythonic/numpy/append.hpp
- pythran/tests/test_numpy_func2.py
> Implement numpy.append when appending a scalar

- pythran/pythonic/include/numpy/setdiff1d.hpp
- pythran/pythonic/numpy/setdiff1d.hpp
- pythran/tables.py
- pythran/tests/test_numpy_func3.py
> numpy.setdiff1d implementation

- pythran/optimizations/inline_builtins.py
- pythran/optimizations/iter_transformation.py
- pythran/tests/test_optimizations.py
- remove spurious array call in presence of Read once functions
- explicitly perform unary/binary op broadcasting on fixed-size arrays
Fix #1060
> Optimize away various numpy.array usage

- pythran/pythonic/include/numpy/append.hpp
- pythran/pythonic/numpy/append.hpp
- pythran/tests/test_numpy_func2.py
Not the most efficient implementation though.
> Extend numpy.append support to all numpy expr

- README.rst
- requirements.txt
- setup.py
looks like it's no longer necessary to rely on a hack, numpy code base improved!
> Use proper dependency handling for numpy

- pythran/toolchain.py
> Also set python version when generating pure c++

- pythran/pythonic/__builtin__/dict/iteritems.hpp
- pythran/pythonic/__builtin__/dict/iterkeys.hpp
- pythran/pythonic/__builtin__/dict/itervalues.hpp
- pythran/pythonic/__builtin__/dict/popitem.hpp
- pythran/pythonic/include/__builtin__/dict/iteritems.hpp
- pythran/pythonic/include/__builtin__/dict/iterkeys.hpp
- pythran/pythonic/include/__builtin__/dict/itervalues.hpp
- pythran/pythonic/include/__builtin__/dict/popitem.hpp
> Avoid useless copies for some dict operations

- pythran/tables.py
> Be less strict when overriding argspec

- pythran/backend.py
- pythran/tests/openmp.legacy/pythran_private.py
> Fix declaration of priavte variables in OMP

- pythran/pythonic/include/numpy/expand_dims.hpp
- pythran/pythonic/numpy/expand_dims.hpp
- pythran/tables.py
- pythran/tests/test_numpy_func2.py
> Implement expand_dims

- pythran/pythonic/include/types/combined.hpp
This should fix #1266 cc @diorcety
> Handle rvalue reference in __combined

- pythran/tables.py
- pythran/tests/test_numpy_func2.py
> Register argsort and put as methods and not functions

- pythran/pythonic/include/types/tuple.hpp
- pythran/pythonic/numpy/empty.hpp
- pythran/pythonic/numpy/ones.hpp
- pythran/pythonic/numpy/zeros.hpp
- pythran/tests/test_ndarray.py
> Fix interaction between static_list and ones/zeros/empty

- pythran/analyses/aliases.py
- pythran/tests/test_optimizations.py
> Fix invalid aliasing computation in subscripts

- pythran/pythonic/include/types/numpy_gexpr.hpp
- pythran/spec.py
Both spec and none slice had buggy behavior, this should be fixed as of
now.
> Fix extended expression slicing

- pythran/pythonic/include/types/numpy_vexpr.hpp
- pythran/tests/test_ndarray.py
> Fix vexpr interaction with static shapes

- pythran/pythonic/include/types/NoneType.hpp
- pythran/pythonic/types/NoneType.hpp
Fix compilation with last msvc version
> Fix MSVC compilation with NoneType std::get

- pythran/pythonic/include/numpy/isnan.hpp
- pythran/pythonic/numpy/isnan.hpp
> Fix compilation with isnan on Windows

- pythran/toolchain.py
PythranExtension already handles them correctly
> Avoid duplication of extension flags

- pythran/pythonic/include/numpy/sort.hpp
- pythran/pythonic/numpy/sort.hpp
- pythran/tests/test_numpy_func0.py
> Support kind argument for numpy.sort

- pythran/pythonic/include/numpy/random/randint.hpp
- pythran/pythonic/numpy/random/randint.hpp
- pythran/tables.py
- pythran/tests/test_numpy_random.py
> Support default arguments for numpy randint

- pythran/conversion.py
- pythran/tests/test_optimizations.py
- pythran/transformations/handle_import.py
- pythran/utils.py
> Take into account cxx_keywords when generating dtype

- pythran/analyses/is_assigned.py
- pythran/backend.py
- pythran/tests/test_none.py
- pythran/transformations/normalize_static_if.py
> Do not outline local definitions when building static_if

- pythran/optimizations/list_to_tuple.py
- pythran/tests/test_numpy_func2.py
> Try hard to force tuple argument for np.concatenate

- pythran/pythonic/numpy/arange.hpp
- pythran/tests/test_numpy_func2.py
> Fix arange for integral numbers

- docs/MANUAL.rst
- pythran/pythonic/include/types/slice.hpp
- pythran/pythonic/types/slice.hpp
- pythran/spec.py
- pythran/tests/test_base.py
- pythran/tests/test_spec_parser.py
- pythran/types/conversion.py
> Support generic slice in pythran spec

- pythran/pythonic/include/types/numpy_expr.hpp
- pythran/pythonic/include/types/tuple.hpp
- pythran/pythonic/types/numpy_expr.hpp
- pythran/tests/__init__.py
This finds more bugs, and a fix for numpy_expr is attached.
> Run validation with assert ON

- pythran/run.py
> Allow slash option on Windows

- docs/CLI.rst
- pythran/pythonic/include/types/numpy_broadcast.hpp
- pythran/tests/test_numpy_broadcasting.py
- pythran/version.py
> Fix numpy broadcast shape

- docs/CLI.rst
- pythran/version.py
- requirements.txt
Freeze gast and beniget dependencies to cope with gast update
> 0.9.3post1

- docs/MANUAL.rst
- pythran/config.py
- pythran/run.py
Not sure whether we want the command-line arguments to override the config flags or not. But this is a start.
> Implement option arguments

- pythran/pythonic/__builtin__/dict.hpp
- pythran/pythonic/__builtin__/type.hpp
- pythran/pythonic/include/__builtin__/bool_.hpp
- pythran/pythonic/include/__builtin__/dict.hpp
- pythran/pythonic/include/__builtin__/int_.hpp
- pythran/pythonic/include/__builtin__/type.hpp
- pythran/pythonic/types/dict.hpp
- pythran/tables.py
- pythran/tests/test_conversion.py
As a side effect, support dict protocol for the dict builtin and the string
conversion for bool and int functor
Fix #1348
> Support the type() builtin

- docs/MANUAL.rst
- pythran/passmanager.py
> Fix documentation and usage of -p flag

- pythran/analyses/cfg.py
- pythran/analyses/static_expressions.py
- pythran/pythonic/__builtin__/isinstance.hpp
- pythran/pythonic/include/__builtin__/isinstance.hpp
- pythran/pythonic/include/__builtin__/pythran/is_none.hpp
- pythran/pythonic/include/types/bool.hpp
- pythran/tables.py
- pythran/tests/test_none.py
- pythran/transformations/normalize_static_if.py
Fix #310
Also improve cfg to handle nested functions, and normalize_static_if to handle
situation where outlined block always returns.
> Support isinstance builtin

- pythran/syntax.py
- pythran/tests/test_advanced.py
Due to gast upgrade + add a test case
> Fix Ellipsis detection

- pythran/types/tog.py
> Constant.s -> Constant.value

- pythran/pythonic/include/types/numpy_texpr.hpp
- pythran/tests/test_ndarray.py
> Fix indexing of a texpr by an array of slices

- .appveyor.yml
- docs/MANUAL.rst
- pythran/pythonic/include/scipy/special/spherical_jn.hpp
- pythran/pythonic/include/scipy/special/spherical_yn.hpp
- pythran/pythonic/scipy/special/spherical_jn.hpp
- pythran/pythonic/scipy/special/spherical_yn.hpp
- pythran/pythonic/types/vectorizable_type.hpp
- pythran/tables.py
- pythran/tests/test_numpy_ufunc_binary.py
- pythran/tests/test_scipy.py
- third_party/boost/math/special_functions/legendre.hpp
- third_party/boost/math/special_functions/spherical_harmonic.hpp
- third_party/boost/math/tools/workaround.hpp
sph_harm, spherical_jn and spherical_yn, only for integer types as first
argument, based on boost/math implementation.
> Adding new special funcs.

- pythran/analyses/constant_expressions.py
- pythran/analyses/range_values.py
- pythran/conversion.py
- pythran/interval.py
- pythran/optimizations/range_based_simplify.py
- pythran/tests/rosetta/permutation_rank.py
Consider tuple of constants as constants, and also fold slices.
> Improve constant folding & forward substitution

- pythran/pythonic/include/numpy/linspace.hpp
- pythran/pythonic/numpy/linspace.hpp
- pythran/tests/test_numpy_func2.py
> Support dtype argument for numpy.linspace

- pythran/intrinsic.py
- pythran/pythonic/__builtin__/max.hpp
- pythran/pythonic/__builtin__/min.hpp
- pythran/pythonic/__builtin__/minmax.hpp
- pythran/pythonic/__builtin__/pythran/kwonly.hpp
- pythran/pythonic/include/__builtin__/max.hpp
- pythran/pythonic/include/__builtin__/min.hpp
- pythran/pythonic/include/__builtin__/minmax.hpp
- pythran/pythonic/include/__builtin__/pythran/kwonly.hpp
- pythran/tables.py
- pythran/tests/test_advanced.py
- pythran/transformations/remove_named_arguments.py
Experimented with max/min key argument for py3
Fix #1355
> Support for kwonly arguments

- .readthedocs.yml
Don't want to add a config file just for that :-)
> Fore installation of scipy w/ rtd

- pythran/backend.py
- pythran/metadata.py
- pythran/middlend.py
- pythran/optimizations/__init__.py
- pythran/optimizations/remove_dead_functions.py
- pythran/pythran.cfg
- pythran/spec.py
- pythran/tests/test_import_all.py
- pythran/tests/test_typing.py
- pythran/toolchain.py
- pythran/transformations/normalize_compare.py
- pythran/transformations/remove_comprehension.py
- pythran/transformations/remove_lambdas.py
- pythran/transformations/remove_nested_functions.py
Based on a Local metadata, set upon function creation and/or based on export set
Fix #1373
> Implement dead function elimination

- docs/MANUAL.rst
> Update export and overloads description in the doc

- pythran/cxxgen.py
- pythran/tests/notebooks/export.ipynb
> Fix handling of overloads when there's only default param

- pythran/pythonic/include/numpy/cross.hpp
- pythran/pythonic/numpy/cross.hpp
- pythran/tables.py
- pythran/tests/test_numpy_func0.py
> Basic support for numpy.cross

- pythran/pythonic/include/numpy/heaviside.hpp
- pythran/pythonic/include/numpy/heaviside/accumulate.hpp
- pythran/pythonic/numpy/heaviside.hpp
- pythran/pythonic/numpy/heaviside/accumulate.hpp
- pythran/pythonic/types/vectorizable_type.hpp
- pythran/tables.py
> Support numpy.heaviside

- README.rst
- docs/MANUAL.rst
- docs/conf.py
- docs/requirements.txt
> Update documentation and doc theme

- docs/CLI.rst
- pythran/spec.py
- pythran/toolchain.py
> Fix function pruning in -e mode

- pythran/pythonic/include/__builtin__/complex.hpp
- pythran/pythonic/include/__builtin__/float_.hpp
- pythran/tests/notebooks/export.ipynb
> Fix dumping str representation of float and complex

- pythran/pythonic/numpy/roll.hpp
No functional change, just code cleaning.
> Cleanup np.roll implementation

- pythran/analyses/extended_syntax_check.py
- pythran/syntax.py
- pythran/tests/test_advanced.py
> Detect unsupported global modification

- pythran/pythonic/include/numpy/arange.hpp
- pythran/pythonic/include/types/numpy_expr.hpp
- pythran/pythonic/types/numpy_expr.hpp
- pythran/tests/test_numpy_func2.py
Not so well optimized, but at least, it works :-/
Fix #1418
> Support slicing of arange

- pythran/intrinsic.py
Fix #1425, but I'm unhappy with the fix
> Increase the default intrinsic argument count

- README.rst
> Update install procedure on OSX

- .travis.yml
- pythran/pythonic/include/types/dynamic_tuple.hpp
- pythran/pythonic/include/types/list.hpp
- pythran/pythonic/include/types/tuple.hpp
- pythran/pythonic/types/tuple.hpp
- pythran/tests/test_advanced.py
> Improve slicing of tuple array

- pythran/config.py
- pythran/run.py
It's now possible to specify --config 'pythran.optimizations=' on the CLI.
> More generic handling of compil options

- pythran/tests/test_ipython.py
> Fix ipython testing

- pythran/pythonic/bisect/bisect.hpp
- pythran/pythonic/operator_/indexOf.hpp
- pythran/tests/test_bisect.py
> Use minimal and explicit exception include in pythonic

- pythran/pythonic/builtins/FileNotFoundError.hpp
- pythran/pythonic/include/builtins/FileNotFoundError.hpp
- pythran/pythonic/include/numpy/fromfile.hpp
- pythran/pythonic/include/types/exceptions.hpp
- pythran/pythonic/numpy/fromfile.hpp
- pythran/pythonic/python/exception_handler.hpp
- pythran/pythonic/types/exceptions.hpp
- pythran/tables.py
- pythran/tests/test_numpy_func0.py
Here's a basic version of fromfile. The sep inputs is currently idgnored (sep is only valid for text files). 
I didn't add a test, not too sure how to do that, write to a temp file?
> Add fromfile

- pythran/conversion.py
- pythran/tests/test_optimizations.py
> Honor shape when folding empty array

- pythran/pythonic/include/numpy/ndarray/tofile.hpp
- pythran/pythonic/numpy/ndarray/tofile.hpp
- pythran/tables.py
- pythran/tests/test_numpy_func0.py
Implemented tofile. sep and format inputs are not supported and throw an error.
> Implement tofile

- pythran/analyses/aliases.py
- pythran/tests/test_typing.py
> Fix error silencing during alias computation

- pythran/pythonic/include/types/ndarray.hpp
- pythran/tests/test_typing.py
> Fix combiner for ndarray expression

- pythran/pythonic/include/types/list.hpp
- pythran/pythonic/types/list.hpp
- pythran/tests/test_list.py
> Implement all required comparison operators for list

- docs/MANUAL.rst
- pythran/tests/test_distutils/setup.py
Credits go to Rodrigo Fischer for spotting them!
> Improve documentation

- docs/MANUAL.rst
- pythran/run.py
- pythran/toolchain.py
> Allow %{ext} substitution in output filename

- .appveyor.yml
- .travis.yml
- pythran/analyses/cfg.py
- pythran/optimizations/forward_substitution.py
- pythran/tests/__init__.py
- pythran/tests/test_optimizations.py
Only forward if the forwarded value can be moved.
Fix #1137
> Fix forward substitution conditions

- pythran/pythonic/numpy/interp.hpp
- pythran/tests/test_numpy_func3.py
> Fix interp implementation in presence of numpy expr

- pythran/pythonic/include/numpy/tile.hpp
- pythran/pythonic/numpy/tile.hpp
- pythran/tests/test_numpy_func0.py
> Fix np.tile implementation when reps count is an array

- pythran/pythonic/types/slice.hpp
- pythran/tests/test_slice.py
Fix #1497. And I though this area was well tested :-/
> Fix normalization of empty slices

- pythran/tests/test_optimizations.py
- requirements.txt
> Bump beniget requirements

- pythran/pythonic/include/types/complex.hpp
- pythran/tests/openmp.4/declare_reduction_complex_implicit.py
> Provide sane default for OpenMP reduction on complex

- pythran/pythonic/numpy/fromfile.hpp
Do not expose too much internals :-)
> Cleaup fromfile implementation

- docs/INTERNAL.rst
- pythran/analyses/__init__.py
- pythran/analyses/ancestors.py
- pythran/analyses/scope.py
- pythran/middlend.py
- pythran/pythonic/include/types/NoneType.hpp
- pythran/pythonic/include/types/static_if.hpp
- pythran/pythonic/numpy/fromfile.hpp
- pythran/tests/test_none.py
- pythran/transformations/__init__.py
- pythran/transformations/normalize_ifelse.py
- pythran/transformations/normalize_static_if.py
> Fix static if normalization in presence of early empty return

- pythran/analyses/is_assigned.py
- pythran/backend.py
- pythran/optimizations/forward_substitution.py
- pythran/tests/test_none.py
- pythran/transformations/normalize_static_if.py
> Fix computation of escaping identifiers for static if

- pythran/tests/test_none.py
- pythran/transformations/normalize_static_if.py
Fix #1540 - that was a stupid one...
> Make normalize static-if behave correctly when nested

- pythran/pythonic/include/numpy/var.hpp
- pythran/pythonic/numpy/var.hpp
- pythran/tests/test_numpy_func0.py
> Fix implementation of numpy.var in presence of complex numbers

- pythran/pythonic/include/utils/nested_container.hpp
- pythran/tests/test_numpy_func2.py
> Fix extraction of dtype for sliced_list

- pythran/pythonic/numpy/sort.hpp
- pythran/tests/test_numpy_func0.py
> Fix sorting of non-array expression

- pythran/dist.py
> Cleanup monkey patching of clang-exe

- pythran/analyses/range_values.py
typical `modify while iterating' error... fix #1556
> Fix range value analysis under py38

- pythran/optimizations/constant_folding.py
- pythran/tests/test_typing.py
- pythran/utils.py
Fix #1554, but the best way would be to have a decent type inference system :-)
> Correctly handle (and report) sequence time float

- docs/MANUAL.rst
> Update documentation with information about blas header

- pythran/pythonic/types/numpy_gexpr.hpp
- pythran/tests/cases/convnet.py
> Properly detect type mismatch when attempting vectorization

- pythran/analyses/aliases.py
- pythran/tests/test_import_all.py
> Properly report invalid nested attribute

- pythran/pythonic/include/numpy/linalg/norm.hpp
- pythran/pythonic/numpy/linalg/norm.hpp
- pythran/tests/test_numpy_linalg.py
> Support complex number and speedup computation for linalg.norm

- pythran/pythonic/numpy/expand_dims.hpp
- pythran/tests/test_ndarray.py
- pythran/tests/test_numpy_func2.py
> Fix expand dim shape access

- docs/MANUAL.rst
- pythran/config.py
> Allow user to *not* use blas at all

- pythran/pythonic/utils/broadcast_copy.hpp
- pythran/tests/test_ndarray.py
> Fix conversion with loop engine

- pythran/pythonic/include/numpy/array.hpp
- pythran/pythonic/include/numpy/asarray.hpp
- pythran/pythonic/numpy/array.hpp
- pythran/pythonic/numpy/asarray.hpp
- pythran/tests/test_numpy_func2.py
> Support scalar mode for np.asarray / np.array

- pythran/analyses/extended_syntax_check.py
- pythran/tests/test_typing.py
> Allow any function as default parameter

- pythran/analyses/cfg.py
- pythran/tests/test_optimizations.py
> Correctly model else clause of for loops

- pythran/pythonic/include/types/numpy_gexpr.hpp
- pythran/pythonic/types/numpy_gexpr.hpp
- pythran/tests/test_ndarray.py
> Fix composition of slices involving new axis

- pythran/analyses/range_values.py
- pythran/tests/test_optimizations.py
> Fix inter-procedural range values

- pythran/analyses/range_values.py
> Fix infinite loop in range values computation

- pythran/analyses/fixed_size_list.py
- pythran/pythonic/include/types/list.hpp
- pythran/pythonic/types/list.hpp
- pythran/tests/test_list.py
> Fix static list detection

- pythran/config.py
- pythran/pythonic/numpy/dot.hpp
> Do not try to include cblas.h if no blas asked

- README.rst
> Update README.rst | Add python color syntax

- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/include/types/numpy_gexpr.hpp
- pythran/pythonic/include/types/numpy_iexpr.hpp
- pythran/pythonic/include/types/numpy_texpr.hpp
- pythran/pythonic/include/types/numpy_vexpr.hpp
- pythran/tests/cases/train_equalizer.py
> Make casting explicit when doing loop conversion

- pythran/cxxtypes.py
This does speed up some type inference part.
Fix #1627
> Do not revisit combined types twice

- pythran/pythonic/types/slice.hpp
- pythran/tests/test_ndarray.py
> Fix composition of fast contiguous slices

- pythran/tables.py
- pythran/transformations/expand_globals.py
Use that information to optimize code generation and store them as static lists
> Global list in pythran cannot have their size changed

- pythran/tests/test_numpy_random.py
> Frail attempt at getting less false positive when testing np.random

- pythran/pythonic/builtins/list/sort.hpp
- pythran/pythonic/include/builtins/list/sort.hpp
- pythran/tables.py
- pythran/tests/test_list.py
> Support list.sort with key argument

- pythran/pythonic/include/types/dynamic_tuple.hpp
- pythran/pythonic/types/dynamic_tuple.hpp
- pythran/tests/test_advanced.py
Proper comparison operators
Extra conversion operator
Fix #1658
> Improve dynamic_tuple API

- pythran/pythonic/include/numpy/empty.hpp
- pythran/pythonic/include/numpy/ones.hpp
- pythran/pythonic/include/numpy/random/random.hpp
- pythran/pythonic/include/numpy/zeros.hpp
- pythran/pythonic/numpy/empty.hpp
- pythran/pythonic/numpy/ones.hpp
- pythran/pythonic/numpy/zeros.hpp
- pythran/tests/test_numpy_func2.py
- pythran/tests/test_numpy_random.py
> Support static size value as numpy.ones/empty/zeros parameters

- pythran/tables.py
- pythran/tests/test_numpy_func0.py
> Improve np.ravel aliasing description

- pythran/run.py
- pythran/spec.py
- pythran/tests/__init__.py
- pythran/tests/notebooks/export.ipynb
- pythran/toolchain.py
- Force file location, even when using pythran in library mode
- Improve file location for spec file
> Improve error reporting

- pythran/pythonic/builtins/file/write.hpp
- pythran/pythonic/include/builtins/file/write.hpp
- pythran/pythonic/include/types/file.hpp
- pythran/pythonic/types/file.hpp
- pythran/tests/test_file.py
> Fix return type of the write method

- pythran/pythonic/include/numpy/fft/hfft.hpp
- pythran/pythonic/include/numpy/fft/ihfft.hpp
- pythran/pythonic/numpy/fft/hfft.hpp
- pythran/pythonic/numpy/fft/ihfft.hpp
- pythran/tables.py
- pythran/tests/test_numpy_fft.py
Here are the promised hfft and ihfft functions. They are pretty straight forward.
> Implement numpy ihfft and hfft functions

- pythran/syntax.py
- pythran/tests/test_cases.py
> Explicitly refuse decorator

- pythran/analyses/locals_analysis.py
- pythran/pythonic/include/numpy/ndarray.hpp
- pythran/pythonic/numpy/ndarray.hpp
- pythran/tests/test_advanced.py
- pythran/transformations/expand_imports.py
> Fix interaction with type annotations

- pythran/analyses/argument_read_once.py
- pythran/tests/test_optimizations.py
> Fix read once effects computation

- pythran/pythonic/builtins/range.hpp
> Fix missing <climit>

- pythran/config.py
> Always honor $HOME for user config lookup

- pythran/pythonic/include/numpy/dot.hpp
- pythran/pythonic/include/types/tuple.hpp
- pythran/pythonic/numpy/dot.hpp
- pythran/tests/test_numpy_func3.py
> Support np.dot between a matrix of dim M and a vector

- pythran/pythonic/include/types/numpy_texpr.hpp
- pythran/pythonic/types/numpy_texpr.hpp
- pythran/tests/test_slice.py
Fix #1758, thanks to @treverhines for the reproducer
> Fix generic slicing of transposed expression

- .github/workflows/parallel.yml
- docs/MANUAL.rst
- pythran/config.py
This is a follow-up to gh-1742 ~and should fix https://github.com/scipy/scipy/issues/13717.~
> Handle LDFLAGS, and use CXXFLAGS instead of CFLAGS

- .github/workflows/core.yml
- pythran/pythonic/types/tuple.hpp
- pythran/tests/scipy/_rbfinterp.py
See https://github.com/scipy/scipy/pull/13595
> Import test case from scipy codebase

- pythran/pythonic/numpy/searchsorted.hpp
Avoid repeated string manipulation when second argument is an array.
Fix #1793
> Fix performance of numpy.searchsorted

- pythran/pythonic/types/raw_array.hpp
> Add missing header

- pythran/config.py
> More robust logic to supress numpy configure checks

- pythran/__init__.py
- pythran/config.py
This should ease integration in other toolchains
> Expose pythran.get_include

- docs/MANUAL.rst
> DOC: modernize "install from source" instructions

- pythran/pythonic/include/types/ndarray.hpp
- pythran/tests/scipy/_sum_abs_axis0.py
> Fix ambiguous combiner for ndarray + none_type

- pythran/optimizations/constant_folding.py
- pythran/tables.py
Instead, use a degraded mode where introspection cannot be used and constant
folding is disabled for the functions in that package.
> Do not remove a package from supported package when it's not available

- pythran/pythonic/include/numpy/transpose.hpp
- pythran/tests/test_numpy_func1.py
> Properly handle transposed expression

- pythran/pythonic/include/types/numpy_expr.hpp
- pythran/tests/cython/setup_add.py
- pythran/tests/test_cython.py
This one has been lagging around for too long... And it should be back to normal
now. Entschuldigung @scoder !
Should fix #1706.
> Restore cython testing and fix pythran header accordingly

- pythran/tests/scipy/_calc_binned_statistic.py
- pythran/tests/scipy/_hypotests.py
Import `scipy/stats/_calc_binned_statistic_pythran.py` and `scipy/stats/_hypotests_pythran.py`
cc @rgommers @serge-sans-paille
> Import test cases from scipy

- pythran/pythonic/include/types/tuple.hpp
- pythran/tests/test_advanced.py
> Improve combiner for tuple and indexable container

- Changelog
> Fix typos in Changelog

- pythran/tests/__init__.py
- pythran/tests/test_ndarray.py
> Tentative portability fix for memory error test

- pythran/config.py
- pythran/toolchain.py
> Make sure pythran always properly closes the file it compiles

- docs/CLI.rst
- pythran/version.py
> Bump dev version number

- docs/CLI.rst
- pythran/tables.py
- pythran/version.py
We should properly ignore an import Failure during init
Fix #1844
> Fix interaction with OpenMP import

- pythran/tables.py
- pythran/tests/test_named_parameters.py
> Fix interaction between getfullargspec and intrinsics without default

- pythran/tables.py
- pythran/tests/test_numpy_func0.py
> Register np.searchsorted as a method and not a function

- pythran/syntax.py
There's nothing preventing its support in pythran, probably through expression
splitting, but that's for another day ;-)
> Advertise lack of named expression support

- pythran/analyses/range_values.py
- pythran/tests/cases/collatz_modified.py
> Fix and simplify range values analysis

- pythran/pythonic/builtins/range.hpp
- pythran/pythonic/include/builtins/map.hpp
- pythran/pythonic/include/builtins/range.hpp
- pythran/pythonic/include/itertools/combinations.hpp
- pythran/pythonic/include/itertools/count.hpp
- pythran/pythonic/include/itertools/ifilter.hpp
- pythran/pythonic/include/itertools/islice.hpp
- pythran/pythonic/include/itertools/permutations.hpp
- pythran/pythonic/include/itertools/product.hpp
- pythran/pythonic/include/itertools/repeat.hpp
- pythran/pythonic/include/types/set.hpp
- pythran/pythonic/itertools/islice.hpp
- pythran/tests/test_set.py
> Correctly handle combiner with range

- pythran/pythonic/types/ndarray.hpp
- pythran/tests/test_ndarray.py
A.k.a correctly handle strides with dimensions 0 or 1
Fix #1864
> Accept some views as regular plain arrays

- pythran/pythonic/types/numpy_gexpr.hpp
> Take into account various specifier when checking gexpr aliasing

- omp/__init__.py
Recently introduced in gh-1856.
Closes https://github.com/scipy/scipy/issues/14687
> BUG: fix issue in libomp detection ImportError

- pythran/pythonic/include/builtins/isinstance.hpp
- pythran/tests/test_none.py
> Support isinstance when second argument is a tuple

- pythran/pythonic/include/numpy/interp.hpp
- pythran/pythonic/numpy/interp.hpp
- pythran/pythonic/numpy/interp_core.hpp
- pythran/tests/test_numpy_func3.py
I specialized interp for numeric types. Let me know if the way I did it isn't righ.
> Add specialization for double for interp function

- pythran/config.py
> Honor quotes in config files

- pythran/analyses/aliases.py
- pythran/syntax.py
- pythran/tests/test_typing.py
- pythran/transformations/normalize_method_calls.py
Based on beniget built-in support \o/
> Properly report all undefined values

- pythran/pythonic/types/list.hpp
- pythran/tests/test_list.py
> Fix sliced list assignment

- pythran/pythonic/include/numpy/dot.hpp
- pythran/pythonic/numpy/dot.hpp
- pythran/tests/test_numpy_func3.py
> Implement dot specialization for transposed M x V and V x M

- pythran/pythonic/include/types/ndarray.hpp
- pythran/tests/test_ndarray.py
- pythran/tests/test_numpy_func3.py
> Allow indexing of ndarray by integers of mixed types

- pythran/pythonic/include/numpy/arange.hpp
- pythran/pythonic/types/numpy_expr.hpp
- pythran/pythonic/utils/broadcast_copy.hpp
To my great shame, that path got removed at some point.... There's no reason for
us to do so.
Fix #1948
> Reactivate xsimd fast path

- pythran/analyses/__init__.py
- pythran/analyses/aliases.py
- pythran/analyses/ast_matcher.py
- pythran/tables.py
- pythran/tests/test_optimizations.py
- pythran/transformations/remove_lambdas.py
- pythran/types/type_dependencies.py
- recognize common operator.*
- avoid creating the same lambda twice
Fix #1963
> Improve lambda removal

- pythran/tests/test_distutils.py
Use correct executable when running import tests.
Should fix #1981
> Harden distutils tests

- pythran/optimizations/pattern_transform.py
Instead of trying to match every node, dispatch based on the type.
Harder, Better, Faster, Stronger.
> Improve pattern matching implementation

- Changelog
- docs/conf.py
Properly set import path
Fix #1990
> Autonomous doc building with sphinx

- pythran/pythonic/include/numpy/argsort.hpp
- pythran/pythonic/numpy/argsort.hpp
- pythran/tests/test_numpy_func2.py
> Support axis parameter in numpy.argsort

- pythran/pythonic/include/numpy/fft/fftn.hpp
- pythran/pythonic/numpy/fft/c2c.hpp
- pythran/pythonic/numpy/fft/fftn.hpp
- pythran/tables.py
- pythran/tests/__init__.py
- pythran/tests/test_numpy_fft.py
> Add support for numpy.fft.fftn

- pythran/pythonic/types/set.hpp
- pythran/tests/test_set.py
> Set intersection fix

- pythran/pythonic/include/scipy/special/gammaincinv.hpp
- pythran/pythonic/include/scipy/special/ndtr.hpp
- pythran/pythonic/include/scipy/special/ndtri.hpp
- pythran/pythonic/scipy/special/gammaincinv.hpp
- pythran/pythonic/scipy/special/ndtr.hpp
- pythran/pythonic/scipy/special/ndtri.hpp
- pythran/tables.py
- pythran/tests/test_numpy_ufunc_unary.py
- third_party/boost/math/distributions/complement.hpp
- third_party/boost/math/distributions/detail/common_error_handling.hpp
- third_party/boost/math/distributions/detail/derived_accessors.hpp
- third_party/boost/math/distributions/fwd.hpp
- third_party/boost/math/distributions/normal.hpp
> Support scipy.special.gammaincinv

- pythran/pythonic/include/numpy/clip.hpp
- pythran/pythonic/numpy/clip.hpp
- pythran/tests/test_numpy_func2.py
> Support np.clip(v, None, x) and np.clip(v, x, None)

- pythran/pythonic/types/ndarray.hpp
- pythran/tests/test_ndarray.py
As usual, untested code means buggy code :-)
Fix #2045
> Correctly convert strided array with offset

- docs/CLI.rst
Should fix #2044, I don't understand why this was validating before
> Fix cli doc test

- pythran/pythonic/numpy/roll.hpp
- pythran/tests/test_numpy_func0.py
> Fix np.roll* on empty arrays

- pythran/pythonic/utils/nested_container.hpp
- pythran/tests/test_advanced.py
Thanks @jeanlaroche for spotting this.
> Do *not* dereference a pointer to an empty container

- pythran/pythonic/include/types/numpy_broadcast.hpp
- pythran/pythonic/include/types/numpy_iexpr.hpp
- pythran/pythonic/include/types/numpy_op_helper.hpp
- pythran/pythonic/numpy/argmax.hpp
- pythran/pythonic/numpy/argmin.hpp
- pythran/pythonic/numpy/argminmax.hpp
- pythran/pythonic/types/numpy_broadcast.hpp
- pythran/tests/cases/lttb_pt.py
Showcased by lttb_pt translated and provided by Stefan van der Walt, which I am thankful to for the effort.
> Fix bad interaction between broadcasting, indexing and numpy expr

- pythran/pythonic/include/utils/numpy_conversion.hpp
- pythran/pythonic/utils/numpy_conversion.hpp
- pythran/tests/test_numpy_func0.py
> Allow more expressions as numpy function parameters

- pythran/pythonic/types/dict.hpp
- pythran/tests/test_dict.py
> Prevent ambigouous overload due to ADL

- docs/MANUAL.rst
Include:
- transitive dependencies (boost, xsimd)
- using Pythran as a transpiler
- change `distutils` to `setuptools`
- details related to cross compilation (xref gh-1394)
Also add notes on `xsimd` always being required, and `USE_XSIMD` turning on vectorization while the default is using `xsimd`'s scalar mode (xref gh-1999).
> Add more docs about using Pythran in a Python package

- pythran/pythonic/include/numpy/ndarray/view.hpp
- pythran/pythonic/include/types/ndarray.hpp
- pythran/pythonic/include/utils/shared_ref.hpp
- pythran/pythonic/numpy/ndarray/view.hpp
- pythran/pythonic/utils/shared_ref.hpp
- pythran/tables.py
- pythran/tests/test_ndarray.py
This allows bitwise casting between different types.
Fix #2112
> Support numpy.ndarray.view

- pythran/pythonic/include/builtins/enumerate.hpp
- pythran/tests/test_advanced.py
> Fix ambiguous value_type in enumerate

- pythran/tests/scipy/_solve_toeplitz.py
> Added test case _solve_toeplitz.py

- pythran/pythonic/include/types/assignable.hpp
> Add missing std::forward

- pythran/tables.py
Instead of catching all exceptions at once, do it at a finer grain to avoid catching by passing real issues.
Also only commit the table entries only once all changes have been made, avoiding intermediate states.
> Cleaner exception handling when filling global tables

- pythran/cxxgen.py
> Fix call to Py_BuildValue in module init

- .github/workflows/core.yml
- pythran/pythonic/builtins/next.hpp
- pythran/pythonic/include/types/assignable.hpp
- pythran/pythonic/include/types/variant_functor.hpp
- pythran/pythonic/types/variant_functor.hpp
- pythran/tests/cases/train_eq.py
- pythran/tests/test_typing.py
Do not forward scalar argument types.
Fix #2132
> Fix call argument forward signature

- pythran/pythonic/include/types/ndarray.hpp
- pythran/tests/test_ndarray.py
> Provide support for constant indexing of numpy vexpr

- pythran/run.py
- pythran/tables.py
- pythran/tests/test_typing.py
> Update signatures for numpy.random

- docs/DEVGUIDE.rst
- pythran/tests/__init__.py
- pythran/tests/test_bisect.py
- pythran/tests/test_itertools.py
- pythran/tests/test_math.py
- pythran/tests/test_ndarray.py
- pythran/tests/test_numpy_broadcasting.py
- pythran/tests/test_numpy_fft.py
- pythran/tests/test_numpy_func0.py
- pythran/tests/test_numpy_func1.py
- pythran/tests/test_numpy_func2.py
- pythran/tests/test_numpy_func3.py
- pythran/tests/test_numpy_linalg.py
- pythran/tests/test_numpy_random.py
- pythran/tests/test_numpy_ufunc_binary.py
- pythran/tests/test_numpy_ufunc_unary.py
- pythran/tests/test_operator.py
- pythran/tests/test_os.py
- pythran/tests/test_random.py
- pythran/tests/test_scipy.py
- pythran/tests/test_time.py
I never use it and we get some warnings about it.
> Remove pytest.mark.module usage

- pythran/pythonic/include/types/list.hpp
- pythran/pythonic/types/list.hpp
- pythran/tables.py
- pythran/tests/test_list.py
I added the implementation of clear() for list. Note that I'm really not sure that my code is best way to do that (call erase(x) repeatedly)
> Add support for clear for lists

- pythran/pythonic/types/numpy_gexpr.hpp
- pythran/tests/test_ndarray.py
> Correctly handle ovelapping detection between gexpr and vexpr

- docs/MANUAL.rst
- pythran/config.py
> Provide support for '--ignore-pythranrc'

- pythran/pythonic/types/bool.hpp
- pythran/tables.py
- pythran/tests/test_ndarray.py
> Fix numpy bool type conversion, and properly support np.bool_

- pythran/pythonic/include/types/list.hpp
- pythran/tests/test_ndarray.py
> Add missing baseid() method for sliced list

- docs/MANUAL.rst
- pythran/cxxgen.py
- pythran/pythonic/include/types/numpy_ufunc.hpp
- pythran/spec.py
- pythran/tests/notebooks/ufunc.ipynb
- pythran/toolchain.py
> Add basic support for generation of ufunc

- pythran/pythonic/types/ndarray.hpp
> FIx leak on slices when converting a gexpr back to python

- pythran/pythonic/include/utils/shared_ref.hpp
- pythran/pythonic/utils/shared_ref.hpp
This is a critical bug, thanks a lot to Tansu Kefeli for raising the issue off-list.
> Fix massive memory leakage in all ndarray

- pythran/pythonic/include/numpy/dot.hpp
Current implementation was just always returning false :-/
> Fix is_blas_array trait

- .github/workflows/core.yml
- docs/MANUAL.rst
- pyproject.toml
- pythran/config.py
- pythran/tests/test_distutils.py
- pythran/tests/test_distutils/meson.build
- pythran/tests/test_distutils/pythran.rc
> Test meson integration

- pythran/optimizations/constant_folding.py
- pythran/tests/test_optimizations.py
> [constant folding] Correctly model restrict_assign in constant folding

- pythran/tests/test_none.py
- pythran/transformations/normalize_static_if.py
> Fix interaction between static if and nested loop / function

- pythran/analyses/inlinable.py
- pythran/dist.py
- pythran/optimizations/inlining.py
- pythran/tests/test_optimizations.py
> Disable inlining in while test

- pythran/tests/__init__.py
> [test] Fix sign comparison code

- pythran/analyses/__init__.py
- pythran/analyses/cfg.py
- pythran/analyses/global_declarations.py
- pythran/analyses/imported_ids.py
- pythran/syntax.py
- pythran/tests/test_nested_functions.py
- pythran/transformations/remove_nested_functions.py
- pythran/unparse.py
> Add support for nonlocal keyword

- pythran/analyses/argument_read_once.py
- pythran/intrinsic.py
- pythran/tests/test_nested_functions.py
- pythran/tests/test_typing.py
- pythran/types/types.py
Still very naive, but that should be a decent start. Fix #2300
> More flexible implementation of default list

- .github/workflows/core.yml
- .github/workflows/dist.yml
- .github/workflows/doc.yml
- .github/workflows/freethreading.yml
- .github/workflows/icc.yml
- .github/workflows/no-setuptools.yml
- .github/workflows/parallel.yml
- pythran/optimizations/forward_substitution.py
- pythran/pythonic/include/utils/seq.hpp
- pythran/tests/test_math.py
- pythran/types/types.py
> Only register a node in name_to_nodes if the combiner was succesful

- pythran/analyses/scope.py
- pythran/backend.py
- pythran/tests/test_typing.py
- pythran/types/types.py
> Traverse augassign when computing scopes

- Changelog
> Add missing changelog entry for 0.18.0

- .github/workflows/core.yml
- pythran/pythonic/builtins/map.hpp
- pythran/pythonic/builtins/range.hpp
- pythran/pythonic/include/builtins/map.hpp
- pythran/pythonic/include/builtins/range.hpp
- pythran/pythonic/include/numpy/ndenumerate.hpp
- pythran/pythonic/include/numpy/ndindex.hpp
- pythran/pythonic/include/types/array.hpp
- pythran/pythonic/include/types/numpy_expr.hpp
- pythran/pythonic/include/types/str.hpp
- pythran/pythonic/types/list.hpp
> Activate -D_GLIBCXX_DEBUG on CI

- .github/workflows/windows.yml
- docs/TUTORIAL.rst
- pythran/tests/test_xdoc.py
- pythran/utils.py
Meanwhile, provide a small workaround
> Gast is not doing its portability job there, this needs to be fix

- pythran/pythonic/numpy/linspace.hpp
- pythran/tests/test_numpy_func2.py
> Fix issue with linspace

- pythran/cxxtypes.py
- pythran/types/types.py
Also use std::result_of_t and std::tuple_element_t in some construction.
> Replace cxxtypes.Decltype by cxxtype.FunctionType which is more accurate

- .github/workflows/core.yml
- README.rst
> Test and document Python 3.14 support

- pythran/pythonic/numpy/ndarray/sort.hpp
- pythran/tests/test_numpy_func0.py
> Sort array of float / doubles according to recent numpy behavior
