pythran/optimizations/square.py, pythran/pythonic/numpy/power.hpp, pythran/tests/cases/ln.py
Doing so makes it possible to achieve > x10 speedup while keeping numpy
correctness.
=> Do not rely on nt2::pow when index is a known integer

pythran/analyses/ast_matcher.py, pythran/tests/test_optimizations.py
ast matcher could not match a NaN litteral as comparison between nan is
always false.
Fixes #401
=> Nan comparison leads to an infinite loop in the optimization loop

omp/__init__.py, pythran/pythonic/types/ndarray.hpp, pythran/tests/cases/euler14.py, pythran/tests/test_base.py, setup.py
If the subprocess call used to detect libgomp fails, just give up this path and let the
remaining part raise an ImportError.
=> Do not raise a random error if omp detection fails

README.rst
Boost.Python moved to a separate `boost-python` package; installing boost `--with-python` is a no-op now.
=> README: Homebrew moved Boost.Python

pythran/tables.py
copyto and isclose numpy methods are not always implemented, depending of the version of numpy
=> Detection of unimplemented numpy methods in order to avoid their use

README.rst
python-dev doesn't seem to be installed by libboost-python-dev, at least I had to install it after getting an error "pyconfig.h no such file or directory in wrap_python.py" when running pythran on a sample code.
=> Add python-dev dependency to README.srt

pythran/pythonic/include/random/shuffle.hpp, pythran/pythonic/random/shuffle.hpp, pythran/tables.py, pythran/tests/test_random.py
I tried adding the other version, with a custom random number generator:
```cpp
template <class T, class function>
void shuffle(T & seq, function && randf) {
std::shuffle(seq.begin(), seq.end(), [&](int min, int max) -> int {
return (max - min) * randf() + min;
});
}
```
This works when calling it like that:
```python
import random
dests = range(64)
random.shuffle(dests, random.random)
print dests
```
but this fails:
```python
import random
dests = range(64)
def f():
return 0.0
random.shuffle(dests, f)
print dests
```
So I didn't add the second version of `random.shuffle`.
=> Add random.shuffle(seq)

.gitignore, README.rst
It looks like installing numpy does not install blas on Debian testing. Can anybody else confirm?
=> Adding blas dependency for Debian in README

setup.py
urllib.urlopen is deprecated and wasn't working on my setup, switching to urllib2 fixes it.
Additionally In some cases (in urllib) the file downloaded wasn't the zip file but an error page (http 404). Adding a check in case this happens.
=> Fixing nt2 DL in setup.py

README.rst
I am not sure if this https://github.com/serge-sans-paille/pythran/issues/350 is still valid, but I think install `pythran` from conda is the easiest way. 
I am myself not a fan of using 'sudo' since I am always working on shared cluster.
=> add conda build

pythran/pythonic/__builtin__/enumerate.hpp, pythran/pythonic/include/__builtin__/enumerate.hpp, pythran/pythonic/include/itertools/imap.hpp, pythran/pythonic/include/types/nditerator.hpp, pythran/tests/cases/check_mask.py
As pointer out by a FIXME, the enumerate object was eventually holding a
dangling reference.
As a side effect remove an old iterator::reference artifact.
Added a test case from stack overflow pointing out the issue!
=> Fix enumerate over an ndarray corner case

pythran/pythonic/include/numpy/around.hpp, pythran/pythonic/include/numpy/round.hpp, pythran/pythonic/include/numpy/round_.hpp, pythran/pythonic/include/utils/numpy_traits.hpp, pythran/pythonic/numpy/around.hpp, pythran/pythonic/numpy/round.hpp, pythran/pythonic/numpy/round_.hpp, pythran/pythonic/types/vectorizable_type.hpp, pythran/tests/cases/goodExpoMeasure.py
They are explicitly described as alias to numpy.around, so why did we
reimplemented both versions o_O
=> Complete implementation of numpy.round and numpy.round_

pythran/analyses/__init__.py, pythran/analyses/inlinable.py, pythran/optimizations/__init__.py, pythran/optimizations/inlining.py, pythran/pythran.cfg
* Usefull to propagate more expression template.
I did some test with
```
#pythran export bar(float[])                                                     
import numpy                                                                     
def foo(a):                                                                      
return numpy.cos(a)                                                          
def bar(c):                                                                      
return foo(c) + c * foo(c)  
```
and I am 10% faster. (On my slow computer...)
=> Add inlining optimisation.

pythran/analyses/cfg.py, pythran/transformations/normalize_return.py
The *[Creating a graph][1]* section of the NetworkX documentation states, "Note: Python’s None object should not be used as a node as it determines whether optional function arguments have been assigned in many functions." For example, if I want to get the dictionary of node degrees, normally I would do `dict(G.degree())` but that causes an error due to the `None` node. This commit changes the sink node to be a special sentinel object, `NIL`.
[1]: http://networkx.readthedocs.io/en/latest/tutorial/tutorial.html#creating-a-graph
=> Uses object instead of None as node in CFG.

pythran/analyses/literals.py
According to the documentation for the built-in [`isinstance`][1] function, "If `classinfo` is a tuple of type objects (or recursively, other such tuples), return true if `object` is an instance of any of the types." This commit replaces custom `any` checking with this form of `isinstance`.
[1]: https://docs.python.org/3/library/functions.html#isinstance
=> Uses tuple second argument to isinstance

pythran/pythonic/include/types/list.hpp, pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/include/types/numpy_broadcast.hpp, pythran/pythonic/include/types/numpy_expr.hpp, pythran/pythonic/include/types/numpy_fexpr.hpp, pythran/pythonic/include/types/numpy_gexpr.hpp, pythran/pythonic/include/types/numpy_iexpr.hpp, pythran/pythonic/include/types/numpy_texpr.hpp, pythran/pythonic/include/types/tuple.hpp, pythran/pythonic/include/types/vectorizable_type.hpp, pythran/pythonic/include/utils/broadcast_copy.hpp, pythran/pythonic/numpy/reduce.hpp, pythran/pythonic/types/list.hpp, pythran/pythonic/types/ndarray.hpp, pythran/pythonic/types/numpy_broadcast.hpp, pythran/pythonic/types/numpy_expr.hpp, pythran/pythonic/types/numpy_fexpr.hpp, pythran/pythonic/types/numpy_gexpr.hpp, pythran/pythonic/types/numpy_iexpr.hpp, pythran/pythonic/types/numpy_texpr.hpp, pythran/pythonic/types/tuple.hpp, pythran/pythonic/utils/broadcast_copy.hpp
The issue is that to achieve broadcasting, we need a dynamic test in the
inner expression template loop. No way around I could find.
So let's add a preliminary check on the ET, and if the ET appear to
*not* need any broadcasting, then another vectorization loop, condition
free, is selected at runtime (which means both version are actually
compiled).
=> Fix subtle performance issue with vectorisation & broadcasting

pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/types/ndarray.hpp
Cython still uses deprecated Numpy APIs!
=> Do not disable deprecated Numpy API when compiling from Cython

pythran/pythonic/include/types/complex.hpp, pythran/tests/test_complex.py
For instance, support std::comple<double> + std::complex<long double> by
casting the first operand to a std::complex<long double>.
=> Support binary operations between different complex types

pythran/pythonic/include/operator_/and_.hpp, pythran/pythonic/include/operator_/lshift.hpp, pythran/pythonic/include/operator_/or_.hpp, pythran/pythonic/include/operator_/rshift.hpp, pythran/pythonic/include/operator_/xor_.hpp, pythran/pythonic/operator_/and_.hpp, pythran/pythonic/operator_/lshift.hpp, pythran/pythonic/operator_/or_.hpp, pythran/pythonic/operator_/rshift.hpp, pythran/pythonic/operator_/xor_.hpp
Inferred type was incorrect, which resulted in extra conversions.
=> Fix bitwise operator output type for uint8

doc/MANUAL.rst, pythran/spec.py, pythran/tests/cases/multitype.py
Make it possible to declare union type to declare multiple overload in a
convenient manner.
Original idea from Yann Diorcet, revisited by serge-sans-paille.
=> Simplify spec declaration through the or operator

pythran/tables.py
=> Manage inspect.getargspec API change between 2.7 and 3.6.1

pythran/config.py
It seems like environment variables have to be set as ASCII, while configparser reads them as unicode. I stumbled over this when simply importing `PythranExtension` was affecting Cython extensions as well.
=> Fix for issue #687

.travis.yml, pythran/magic.py
Hi @serge-sans-paille 
As described during the pythran tutorial, pull request to fix the cell (type: str) encoding bug.
Best,
Florian
=> encoded content of cell (type: str) to avoid hashlib error

pythran/pythonic/include/numpy/power.hpp, pythran/tests/test_math.py
Probably due to boost::simd::pow implementation, fixed forcing the
operand type to the common one.
Fix #708
=> Fix pow accuracy issue

docs/INTERNAL.rst, docs/MANUAL.rst, pythran/cxxgen.py, pythran/pythonic/include/types/pointer.hpp, pythran/pythonic/types/pointer.hpp, pythran/pythonic/types/str.hpp, pythran/pythran-linux.cfg, pythran/pythran-linux2.cfg, pythran/spec.py, pythran/syntax.py, pythran/tests/test_env.py, pythran/tests/test_numpy_ufunc_unary.py, pythran/tests/test_openmp.py, pythran/tests/test_spec_parser.py, pythran/toolchain.py, pythran/types/conversion.py, pythran/types/tog.py, pythran/types/type_dependencies.py, pythran/typing.py
This can be used by third-party library like scipy.LowLevelCallable to
avoid conversion costs.
=> Export native function pointer through __natives__

pythran/tables.py
Subpackage is not enough. Fix #772
=> Remove whole scipy package from MODULES when it's not available

pythran/pythonic/types/ndarray.hpp
It looses accuracy, which result in invalid allocation and such.
Fix #778
=> Fix implicit conversion during accumulate

pythran/pythonic/include/numpy/copy.hpp, pythran/pythonic/include/types/numpy_gexpr.hpp, pythran/pythonic/include/types/numpy_texpr.hpp, pythran/pythonic/numpy/copy.hpp, pythran/pythonic/numpy/var.hpp, pythran/pythonic/types/numpy_gexpr.hpp, pythran/pythonic/types/numpy_texpr.hpp, pythran/tests/test_numpy_func0.py
This avoids a few extra copies and should (partially) fix #805.
=> Conserve memory order during numpy.copy and upon return

pythran/tables.py
matmul was added in python 3.5 (https://docs.python.org/3/whatsnew/3.5.html)
=> Disable @ operator for < 3.5

pythran/pythonic/include/types/combined.hpp, pythran/pythonic/include/types/dict.hpp, pythran/pythonic/types/dict.hpp
Specializing remove_cv was indeed a terrible idea.
=> Fix broken compilation with g++-8

pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/include/types/numpy_gexpr.hpp, pythran/pythonic/types/ndarray.hpp, pythran/pythonic/types/numpy_gexpr.hpp
Probably due to std::tuple_cat misuse, but... who knows?
=> Fix OSX bug when dealing with numpy_gexpr

setup.py
Running python setup.py build_py --no-boost does not distribute boost as
part of pythran, relying on a user-defined configuration through
.pythranrc or system default.
=> Optionally use external boost headers

pythran/config.py, pythran/dist.py, pythran/toolchain.py
Use Pythran BuildExt as *the* standard way to build things, even
internally.
=> Fix compilation setp: honor CXX from pythranrc

pythran/pythonic/include/numpy/power.hpp
Using static dispatch to exponentiation by squaring solves the issue.
=> Fix performance issue with np.power when second argument is an integer

third_party/xsimd/math/xsimd_scalar.hpp
=> Fix xsimd scalar sincos implementation on OSX

pythran/pythonic/include/types/numpy_broadcast.hpp
This prevents effective vectorization, due to type mismatch. Maybe we
should delegate that to xsimd?
=> Do not optimize complex broadcasting under SIMD mode

pythran/log.py
This is especially important for packages that depend on pythran like cython.
=> Remove annoying colorlog warning

README.rst
`yaourt` is not recommended and frowned upon among Arch Linux people, as it fail to [satisfy many criterias](https://wiki.archlinux.org/index.php/AUR_helpers#Pacman_wrappers) :) . I will maintain the `python-pythran` and `python2-pythran` packages, for which the PKGBUILD is derived from the old PKGBUILD by @xantares. You can see the what the package does below:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-pythran
=> Remove yaourt and unmaintained python2-pythran-git recommendation

pythran/pythonic/utils/broadcast_copy.hpp
Without this modification, the following issue apprears
`pythran\pythonic/utils/broadcast_copy.hpp(71): error C3016: 'i': index variable in OpenMP 'for' statement must have signed integral type`
=> Fix OMP on Windows

pythran/pythonic/include/numpy/arange.hpp, pythran/pythonic/numpy/arange.hpp, pythran/tests/test_env.py, pythran/tests/test_numpy_func2.py, third_party/xsimd/types/xsimd_base.hpp
This speedsup expression like ``np.arange(x) * y``.
=> Make arange a lazy expression

pythran/tests/test_distutils.py, pythran/tests/test_distutils_setuptools/a.py, pythran/tests/test_distutils_setuptools/setup.py
This somehow fixes #326, at least it showcases that bdist is correctly
supported, both as bdist and bdist_wheel.
=> Add extra tests for wheel creation and setuptools integration

pythran/pythonic/__builtin__/tuple.hpp, pythran/pythonic/include/__builtin__/tuple.hpp, pythran/pythonic/include/itertools/combinations.hpp, pythran/pythonic/include/itertools/permutations.hpp, pythran/pythonic/include/types/dynamic_tuple.hpp, pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/include/types/tuple.hpp, pythran/pythonic/itertools/combinations.hpp, pythran/pythonic/itertools/permutations.hpp, pythran/pythonic/types/dynamic_tuple.hpp
This type can be used as a tuple of elements of the same type, with a
size only known at runtime. It is an alternative to types::array,
introduced for situation when the tuple is created from an iterable with
unknown size.
This not a general solution of the list-to-tuple problem, but it helps.
This fixes #1152 and improves #1113.
=> dynamic tuple internal type

docs/MANUAL.rst, pythran/config.py
Allow to override the default .pythranrc path using environment variable PYTHRANRC
=> Support PYTHRANRC environment variable

pythran/toolchain.py
This fixes issue #1098 
@serge-sans-paille can you tell me where I can add a test for this? i didn't find any tests on the `-o` / `output_file` option.
=> support -o toto.cpython-37m-x86_64-linux-gnu.so

pythran/pythonic/__builtin__/str/isdigit.hpp, pythran/pythonic/include/types/tuple.hpp, pythran/pythonic/include/utils/nested_container.hpp, pythran/pythonic/include/utils/numpy_conversion.hpp, pythran/pythonic/utils/numpy_conversion.hpp
Few windows improvements:
cctype missing for std::digit (maybe other headers have this issue)
struct/class warning
Support clang-cl (_MSC_VER + __clang__)
=> Improve Windows compilation

pythran/pythonic/numpy/fft/irfft.hpp, pythran/pythonic/numpy/fft/rfft.hpp, pythran/tests/test_numpy_fft.py
The core C++ routines in numpy.fft are not thread safe because they modify the twiddle factors during the function call (the get restored at the end).
This is to avoid the threading issue: I create a temp copy of the twiddle factors before calling the fft routine. It's not great but it does fix the issue.
=> numpy fft: Copy twiddle factors into local array to make algo thread safe

pythran/pythonic/__builtin__/sorted.hpp, pythran/pythonic/include/__builtin__/sorted.hpp, pythran/tables.py, pythran/tests/test_base.py
Showcased by the sorted builtin, and fixes #1234
=> Implement keyword-only argument extraction for Python3

pythran/pythonic/include/numpy/angle_in_rad.hpp, pythran/pythonic/numpy/angle_in_rad.hpp, pythran/tests/test_numpy_func2.py
This fixes the discrepancy between numpy and pythran for the angle() function.
Numpy uses a 4 quadrant arc-tangent, but pythran was using a regular 2 quadrant arc-tangent.
=> Fix issue with angle

docs/MANUAL.rst, pythran/spec.py, pythran/tests/cases/clip2.py, pythran/tests/cases/julia_pure_python.py, pythran/tests/cases/weights.py, pythran/tests/test_spec_parser.py
#pythran export foo(int, float?, bool?)
def foo(x, y=1., z=True): pass
Does what you would expect :-)
Fix #1242
=> Support default type in pythran spec, through the ? annotation

pythran/pythonic/include/math/ceil.hpp, pythran/pythonic/include/math/floor.hpp, pythran/pythonic/include/math/trunc.hpp, pythran/pythonic/include/numpy/count_nonzero.hpp, pythran/pythonic/include/numpy/rank.hpp, pythran/pythonic/include/numpy/reduce.hpp, pythran/pythonic/include/types/dynamic_tuple.hpp, pythran/pythonic/include/types/exceptions.hpp, pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/math/ceil.hpp, pythran/pythonic/math/floor.hpp, pythran/pythonic/math/trunc.hpp, pythran/pythonic/numpy/count_nonzero.hpp, pythran/pythonic/numpy/rank.hpp, pythran/pythonic/numpy/reduce.hpp, pythran/pythonic/types/exceptions.hpp, pythran/tests/__init__.py, pythran/tests/cases/compute_subpix_2d_gaussian2.py, pythran/tests/cases/pselect.py, pythran/tests/cases/train_eq.py, pythran/tests/rosetta/pythagor_triples.py, pythran/tests/test_base.py, pythran/tests/user_defined_import/mix_builtin.py, pythran/transformations/normalize_compare.py
- ceil/floor/trunc return an int
- max/min don't do type promotion
- exception's args can be stored as dynamic_tuple instead of list
- rank returns an int and not a size_t
- normalize_compare generates bool and not int
This fixes #339 that actually got fixed a while ago, but now we are sure
it won't regress.
Still allow int64 <> long, bool_ <> bool float32 <> float conversion.
=> Stricter type checking between Python and Pythran result

pythran/pythonic/numpy/bincount.hpp
=> Fix std::max usage in numpy.bincount

pythran/analyses/lazyness_analysis.py, pythran/tests/openmp.legacy/pythran_forward_substitution.py
Even the one that no longer exist! Fix #1259
=> Properly handle variables referenced in private/shared omp clause

pythran/tests/test_numpy_random.py
Several tests were using tests like abs(mean(a)) < 3.01 to test that mean(a) was close to 3.
This should have been abs(mean(a)-3) < 0.01 .
=> Fix errors in computing accuracy of means in several tests

pythran/pythonic/types/ndarray.hpp
Thanks to Rodrigo Iga for providing a test case that exhibited the
issue.
=> Fix important memory leak in numpy_gexpr to_python

pythran/pythonic/numpy/interp.hpp, pythran/pythonic/numpy/interp_core.hpp
Problem due to file extension, should be a .hpp t be correclty bundled.
Thanks to Jean Laroche for spotting the issue!
=> Fix packaging of numpy/interp_core.cpp

pythran/analyses/aliases.py
Avoid SyntaxWarnings due to invalid backslash-escapes.
=> \o/ was not intended as a backslash-escape.  Tell python.

pythran/pythonic/include/types/numpy_gexpr.hpp
_S is a preprocessor token on my platform, leading to uninformative
error messages.  I think _other_classes captures the purpose of this
variable.
=> Change _S to _other_classes.

pythran/pythonic/types/slice.hpp
PySlice_Unpack is only supported since 3.6.1
=> Fix compilation with Python < 3.6.1

pythran/backend.py, pythran/tests/openmp.legacy/pythran_collapse.py
Basically generate loop bound in a nested fashion as long as the upperbound is a
pure expression.
Fix #1337
=> Make pythran.Python generator compatible with collapse clause

pythran/pythonic/types/dict.hpp
PyDict_SetItem doesn't take ownership, unlike it's list equivalent :-/
Fix #1384, that's an old leak, thanks a lot to @m-romanov!
=> Fix memory leak when converting a dict to python

docs/INTERNAL.rst, pythran/pythonic/types/slice.hpp
Fixes #1395 
I don't know where PYTHRAN_COMPILING_IN_PYPY should be defined...
=> PyPy3.6 support (no PySlice_Unpack)

pythran/pythonic/include/__builtin__/pythran/is_none.hpp
add #ifdef ENABLE_PYTHON_MODULE for
pythran -e and g++ compile without ENABLE_PYTHON_MODULE
=> fix compile without ENABLE_PYTHON_MODULE

pythran/pythonic/include/types/numpy_broadcast.hpp, pythran/pythonic/types/numpy_expr.hpp, pythran/tests/cases/matrix_class_distance.py
=> Fix shape computation of nexpr when one of the expr is empty

pythran/backend.py, pythran/tests/test_list.py
Just work under the assumption that OpenMP collapse implies a simple ranged
loop. We could probably do a better canonicalization.
Fix #1424
=> Fix interaction between OpenMP collapse and pythran-generated loops

pythran/analyses/inlinable.py, pythran/tests/test_optimizations.py
That would duplicate the side effect at each use site.
=> No inlining of global variable if their initializer has a side effect

pythran/pythonic/include/types/numpy_expr.hpp, pythran/pythonic/include/types/slice.hpp, pythran/tests/test_numpy_broadcasting.py
((5, 1) * (1, 5)) [1:3] cannot be folded into
((5,1)[1:3]) * ((1, 5)[1:3]) without some extra magic.
Fix #1445
=> Fix slicing of a broadcasting numpy_expr

pythran/analyses/aliases.py, pythran/tests/test_import_all.py
In the context of aliases, the name was always used :-/
=> Fix handling of global declaration aliases

pythran/pythonic/include/types/tuple.hpp, pythran/pythonic/numpy/ndarray/reshape.hpp, pythran/tests/test_numpy_func2.py
There's a bug in the current implementation of a.reshape that causes a segmentation fault for calls like a.reshape(-1)
This PR fixes it, and adds a test.
=> Fix a.reshape(-1)

pythran/cxxtypes.py
This generates much cleaner code.
=> Avoid redundancy withing type combiners

pythran/spec.py, pythran/tests/rosetta/proba_choice.py
Default argument list was split in the reverse order...
Modify a rosetta test case to use that spec syntax.
Fix #1508
=> Fix optional argument handling in spec

pythran/backend.py, pythran/tests/test_advanced.py
=> Correctly protect c++ identifiers in local_names

pythran/pythonic/types/numpy_gexpr.hpp, pythran/tests/test_ndarray.py
=> Correctly set buffer when assigning default constructed gexpr

pythran/spec.py, pythran/tests/__init__.py, pythran/tests/test_spec_parser.py, pythran/toolchain.py
This is both invalid (One can forge a content that looks like a path) and
fragile (long content leads to exception on Windows)
Fix #1539
=> Do not try to distinguish between filepath and content in spec_parser

pythran/pythonic/include/types/numpy_gexpr.hpp, pythran/pythonic/include/types/numpy_iexpr.hpp, pythran/pythonic/include/types/numpy_vexpr.hpp, pythran/tests/test_ndarray.py
By default use ndarray to hold the expression in case of mixed type. It's ok
(but sometimes costly) if the expression is in read mode, and not okay if it's a
mixed view to write too...
Fix #1040
=> Fix combiner between ndarray and expression

pythran/dist.py
Avoid the warning
```
pythran/dist.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
from collections import defaultdict, Iterable
```
It should be supported by Python >= 3.3. Python 3.3 was released on Sept. 29, 2012.
Does Pythran need to support Python < 3.3 ? See https://numpy.org/neps/nep-0029-deprecation_policy.html
=> Iterable imported from collections.abc to avoid a warning

pythran/pythonic/include/numpy/add/reduce.hpp, pythran/pythonic/include/numpy/bitwise_and/reduce.hpp, pythran/pythonic/include/numpy/bitwise_or/reduce.hpp, pythran/pythonic/include/numpy/bitwise_xor/reduce.hpp, pythran/pythonic/include/numpy/fmax/reduce.hpp, pythran/pythonic/include/numpy/fmin/reduce.hpp, pythran/pythonic/include/numpy/maximum/reduce.hpp, pythran/pythonic/include/numpy/minimum/reduce.hpp, pythran/pythonic/include/numpy/multiply/reduce.hpp, pythran/pythonic/include/numpy/ufunc_reduce.hpp, pythran/pythonic/include/utils/neutral.hpp, pythran/pythonic/numpy/add/reduce.hpp, pythran/pythonic/numpy/bitwise_and/reduce.hpp, pythran/pythonic/numpy/bitwise_or/reduce.hpp, pythran/pythonic/numpy/bitwise_xor/reduce.hpp, pythran/pythonic/numpy/fmax/reduce.hpp, pythran/pythonic/numpy/fmin/reduce.hpp, pythran/pythonic/numpy/maximum/reduce.hpp, pythran/pythonic/numpy/minimum/reduce.hpp, pythran/pythonic/numpy/multiply/reduce.hpp, pythran/pythonic/numpy/ufunc_reduce.hpp, pythran/pythonic/utils/neutral.hpp, pythran/tables.py, pythran/tests/test_numpy_ufunc_binary.py
Currently, only associative operators are supported due to a limitation in
numpy/reduce.hpp
Fix #844
=> Support reduce function for various numpy operators

docs/MANUAL.rst, pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/include/types/tuple.hpp, pythran/pythonic/include/utils/shared_ref.hpp, pythran/pythonic/types/list.hpp, pythran/pythonic/types/ndarray.hpp, pythran/pythonic/types/tuple.hpp, pythran/pythonic/utils/shared_ref.hpp
Use more asserts throughout the code to check for null pointers and buffer
overflow.
As this behavior is now documented, it should be somehow enforced by more
defensive coding under the protection of NDEBUG.
At some point, it may be interesting to separate checks that also exist in
Python (like IndexError or AssertionError) from internal checks...
This improves the situation wrt #416 but doesn't actually fixes it until the
check split isn't done.
=> Better document NDEBUG behavior

pythran/analyses/argument_effects.py, pythran/analyses/extended_syntax_check.py, pythran/pythonic/include/types/list.hpp, pythran/pythonic/include/types/numpy_iexpr.hpp, pythran/pythonic/include/types/tuple.hpp, pythran/pythonic/types/list.hpp, pythran/tests/test_advanced.py, pythran/tests/test_typing.py
As a side effect, unveil a few bugs in interprocedural typing, some of them
won't be fixed by this commit but still referenced in a skipped test case.
Fix #1579
=> Fix global effect computation for partial functions

requirements.txt
Pythran version are actually bound to gast minor version, let's use the
compatible release version specifier to enforce that.
=> Freeze gast version

pythran/pythonic/builtins/list/sort.hpp, pythran/pythonic/builtins/sorted.hpp, pythran/pythonic/numpy/argsort.hpp, pythran/pythonic/numpy/intersect1d.hpp, pythran/pythonic/numpy/lexsort.hpp, pythran/pythonic/numpy/median.hpp, pythran/pythonic/numpy/setdiff1d.hpp, pythran/pythonic/numpy/sort.hpp, pythran/pythonic/utils/pdqsort.h
Also specialize np.sort along last axis to avoid copies.
Fix #1580
=> Use pdqsort instead of std::sort to match numpy performance

pythran/pythonic/numpy/median.hpp, pythran/tests/test_numpy_func0.py
Makes sure that the argument is not mutated in place in the
re-implementation fo numpy.median.
Fixes  #1588
=> numpy.median: Do not mutate argument inplace

pythran/dist.py
The current os.stat comparison is not correct
=> Fix time comparison for cpp file creation

pythran/pythonic/builtins/str/replace.hpp, pythran/pythonic/numpy/base_repr.hpp, pythran/pythonic/numpy/binary_repr.hpp, pythran/pythonic/numpy/median.hpp, pythran/pythonic/numpy/sort.hpp, pythran/pythonic/types/file.hpp
`new` is used in few places to allocate temporary buffers, work and them
and `delete` them shortly after. Some of the operations done between the
new and delete can be non-`noexcept`, so it is safer to use a `unique_ptr`
to ensure memory release even in (improbable) case of exception.
=> Wrap new-delete in unique_ptr

pythran/pythonic/include/types/str.hpp, pythran/pythonic/numpy/base_repr.hpp, pythran/pythonic/types/str.hpp, pythran/tests/test_numpy_func2.py
Improve the numpy.base_repr implementation by:
- avoiding extra buffer allocation
- only allocate the required memory
=> numpy::base_repr: improve implementation

pythran/pythonic/builtins/str/__mod__.hpp, pythran/pythonic/include/types/str.hpp, pythran/pythonic/numpy/base_repr.hpp, pythran/pythonic/numpy/fromstring.hpp, pythran/pythonic/types/str.hpp
`types::str::get_data` and `types::str::chars` basically does the same thing. Remove `types::str::get_data` and
only use chars in order to avoid duplicated API.
=> types::str: remove get_data since it duplicates chars

pythran/pythonic/builtins/bin.hpp, pythran/pythonic/include/builtins/bin.hpp, pythran/tests/test_base.py
The final length of the string representation can be easily computed
head of time so a stream string is a bit overkill. Prefer a regular
string with storage reserved in advance.
[Quickbench](https://quick-bench.com/q/teJB_p3MpMNwPDqXNnCaPqVng6w) also says this is more efficient (but to be honest, this code will never end up in a critical compute intensive path).
=> builtins::bin: avoid use of std::osstream

pythran/config.py
The arguments returned by pythran-config are incorrect if the compiler is not gcc (cl.exe or even clang-cl.exe).
Using ccompiler methods for getting valid arguments
=> Fix pythran-config with cl.exe or clang-cl.exe

pythran/backend.py, pythran/pythonic/include/types/dynamic_tuple.hpp, pythran/pythonic/include/types/list.hpp, pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/include/types/numpy_broadcast.hpp, pythran/pythonic/include/types/numpy_expr.hpp, pythran/pythonic/include/types/numpy_gexpr.hpp, pythran/pythonic/include/types/numpy_iexpr.hpp, pythran/pythonic/include/types/numpy_texpr.hpp, pythran/pythonic/include/types/numpy_vexpr.hpp, pythran/pythonic/include/types/slice.hpp, pythran/pythonic/include/types/str.hpp, pythran/pythonic/include/types/tuple.hpp, pythran/pythonic/types/list.hpp, pythran/pythonic/types/ndarray.hpp, pythran/pythonic/types/numpy_broadcast.hpp, pythran/pythonic/types/numpy_gexpr.hpp, pythran/pythonic/types/numpy_iexpr.hpp, pythran/pythonic/types/numpy_texpr.hpp, pythran/pythonic/types/numpy_vexpr.hpp, pythran/pythonic/types/slice.hpp, pythran/pythonic/types/str.hpp, pythran/pythonic/types/tuple.hpp, pythran/pythonic/utils/pdqsort.hpp, pythran/types/types.py
This introduces a new type of slices, fast_contiguous_slice, with faster
methods. A direct consequence is the rewrite of most slicing methods to
accommodate this new type.
Fix #1603
=> Use range values to fasten slice computation

pythran/pythonic/builtins/range.hpp, pythran/tests/test_numpy_func0.py, pythran/tests/test_numpy_func2.py
- Do not overflow using 2**32
- Be explicit about array type
This is a partial fix for #1639
=> Fix several testing issues on m32 architectures

pythran/pythonic/numpy/nonzero.hpp
We always use long to store size / indices, but ptrdiff_t may not be a long.
Fix #1644
=> Fix casting issue on windows

pythran/interval.py
When performing an union, intersect or add, a TupleInterval must return a tuple
interval, even of unknown range
=> Fix inconsistency in TupleInterval Handling

pythran/pythonic/numpy/unwrap.hpp, pythran/tests/test_numpy_func3.py
The formula for unwrapping is y += 2*pi * round((x-y)/(2*pi)) (where x is the previous value)
The current formula was y += 2*pi * int((x-y)/(pi)) which is bad on two counts (pi instead of 2pi and not using round)
=> Fix bug in unwrap function

pythran/backend.py, pythran/cxxtypes.py, pythran/pythonic/include/numpy/reduce.hpp, pythran/pythonic/include/operator_/mul.hpp, pythran/pythonic/include/types/assignable.hpp, pythran/pythonic/include/types/numpy_expr.hpp, pythran/pythonic/include/types/numpy_gexpr.hpp, pythran/pythonic/include/types/numpy_iexpr.hpp, pythran/pythonic/include/types/numpy_texpr.hpp, pythran/pythonic/operator_/mul.hpp, pythran/pythonic/types/numpy_nary_expr.hpp
This qualifier makes it possible to take most expression by reference, avoiding
a lot of shared counter manipulation.
Should fix #1668
=> Introduce a new type qualifier, AssignableNoEscape

pythran/pythonic/numpy/nanmax.hpp, pythran/pythonic/numpy/nanmin.hpp, pythran/tests/test_numpy_func0.py
numpy.nanmin and numpy.nanmax do not respect Numpy specification : "When all-NaN slices are encountered a RuntimeWarning is raised and Nan is returned for that slice."
https://numpy.org/doc/stable/reference/generated/numpy.nanmin.html
It seems there is also a problem with all-PINF slices but not checked in details
=> Nanmin nanmax

pythran/middlend.py, pythran/tests/test_base.py, pythran/transformations/__init__.py, pythran/transformations/remove_fstrings.py
Pythran could support some f-strings by converting them into standard formatting with `%`.
It's a naive implementation to see what it's going to break (and increase our CI-based heater).
What would be the correct way to inform the user that something in the code is not supported?
=> Basic support for f-strings (fix #1675)

docs/MANUAL.rst, pythran/dist.py, pythran/tests/test_distutils.py, pythran/tests/test_distutils_numpy/demo3/a.py, pythran/tests/test_distutils_numpy/setup.py
Use a mixture of MixIn and MetaClass to achieve that goal in a pythonic (?) way.
Fix #1692
=> Improve PythranBuildExt to support base class customization

docs/MANUAL.rst, pythran/run.py
This make it possible to avoid usage of pythranrc.
Also sneak a fix config option passing from CLI :-)
Fix #1691
=> Document how to pass config options to PythranExtension

pythran/log.py
I think it's better to avoid `logging.basicConfig` and to set a handle only to pythran's logger so that other loggers are not affected.
Otherwise, when ones creates another logger after `import pythran`, the logger already has a handle inherited from root.
=> Avoid logging.basicConfig

pythran/backend.py, pythran/optimizations/pattern_transform.py, pythran/pythonic/builtins/pow.hpp, pythran/pythonic/include/builtins/pow.hpp, pythran/tests/rosetta/ackermann.py, pythran/tests/test_base.py, pythran/types/types.py, pythran/utils.py
Unless we have a literal exponent. Otherwise we're doomed if the exponent is
negative.
Fix #1730
=> Return a floating point type when computing builtins.pow

pythran/backend.py, pythran/config.py, pythran/tests/__init__.py, pythran/tests/test_typing.py
This make it possible to correctly type tuples that are not bound to a variable.
Fix #1682
Fix #1459
=> Explicitly insert cast on rvalue tuple when needed

pythran/pythonic/include/types/finfo.hpp, pythran/pythonic/types/finfo.hpp, pythran/tests/test_numpy_func0.py
Looks like this was still using an older `getattr` API, and wasn't being caught by the test because it gets optimised away.
=> Fix pythonic interface for numpy.finfo

pythran/pythonic/include/types/finfo.hpp, pythran/pythonic/types/finfo.hpp, pythran/tests/test_numpy_func0.py
Numpy's `finfo` will first cast its argument dtype to a floating instance, particularly in the case of a complex dtype. We add a specialisation to the template to facilitate this.
@serge-sans-paille I must admit I didn't look around too much for whether partial specialisation is the right pattern to use here (or whether I've done it "properly" -- my template C++ is a bit rusty!), I'm happy to use something more project-specific if that's the way to go instead.
=> Make np.finfo.eps float for complex dtype

pythran/pythonic/include/types/ndarray.hpp, pythran/tests/test_ndarray.py
This is implemented for most other ndarray derivatives, but not a plain view. We should be able to transform the underlying object in the same way as e.g. `numpy_iexpr`.
1. Not sure if we should necessarily be accessing `data_` and `view_` on the `numpy_vexpr` directly, but it does seem to fit the same pattern as the other expressions.
2. I guess it's only really `.real` and `.imag` that need this specialisation, but the same pattern is applied a few times -- maybe it'd benefit from an interface to change the view across `iexpr`, `gexpr`, `texpr` and `vexpr`?
=> Forward .real and .imag into numpy_vexpr

README.rst
These stood out to me. `easy_install` has been removed from `setuptools` and should always be avoided even if it's still available on some system. Miniforge is better than Miniconda now, more up-to-date and more fitting because Pythran comes from conda-forge.
[ci skip]
=> Update install instructions, no more `easy_install` & use Miniforge

pythran/types/conversion.py
It's now an alias to builtins.int, no need to register it anymore
Fix #1756
=> numpy.int is deprecated

pythran/pythonic/types/ndarray.hpp
That's a huge fix, thanks a lot to @treverhines for providing a simple
reproducer.
Fix #1761
=> Fix memory leak when calling PyArray_Transpose

pythran/pythonic/include/numpy/transpose.hpp, pythran/pythonic/numpy/transpose.hpp, pythran/pythonic/types/ndarray.hpp, pythran/tests/test_ndarray.py, pythran/tests/test_slice.py
=> Do not create a copy of a 2D expression when transposing it

omp/__init__.py
Currently the SciPy on Windows build gives warnings like:
```
clang-cl: warning: unknown argument ignored in clang-cl: '-print-file-name=libgomp.dylib' [-Wunknown-argument]
clang-cl: error: no input files
clang-cl: warning: unknown argument ignored in clang-cl: '-print-file-name=libgomp.so' [-Wunknown-argument]
clang-cl: error: no input files
```
for every Pythran invocation. This should improve that.
Also fix a str/bytes issue that resulted in invalid paths starting with `b/...` because of calling str() on a bytes object.
=> Improve OpenMP detection for different platforms and compilers

pythran/analyses/aliases.py, pythran/backend.py, pythran/cxxtypes.py, pythran/pythonic/include/types/combined.hpp, pythran/pythonic/include/types/list.hpp, pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/include/types/tuple.hpp, pythran/pythonic/types/list.hpp, pythran/tests/test_cases.py, pythran/types/types.py
This requires a complex interplay between alias analyses, type inference and
combiners.
In `a[1][2]`, `a` is now considered as an indexable container indexed by an
integral constant, which make it possible to properly model tuple accesses;
This should fix #1754
=> Fix combiner between nested structures

pythran/tables.py, pythran/tests/test_ndarray.py
=> Prevent folding of numpy.dtype.type when used as a function

pythran/pythonic/builtins/str/split.hpp, pythran/tests/test_str.py
=> Properly handle empty string during str.split

pythran/tables.py
There are several ways why omp loading may fail, just make sure this doesn't
stop the init process.
Somehow fix #1769
=> Harden handling of third-party imports during init

pythran/pythonic/include/types/numpy_iexpr.hpp, pythran/pythonic/types/numpy_iexpr.hpp, pythran/tests/test_ndarray.py
This is obviously not the best idea when we're holding a const reference, but it
works fine and fix #1787
At some point, We should support setitem / getitem instead of pretending to be
smart with operator[]...
=> Always have numpy_iexpr return a reference

docs/CLI.rst, pythran/tests/test_version.py, pythran/version.py
Using `0.9.12dev` actually broke SciPy CI, because Cython does this:
```
pythran_is_pre_0_9_6 = tuple(map(int, pythran.__version__.split('.')[0:3])) < (0, 9, 6)
```
Add tests to check version string is compliant, taken over from NumPy
=> Fix dev version string to be PEP 440 compliant

pythran/pythonic/__dispatch__/sort.hpp, pythran/pythonic/include/__dispatch__/sort.hpp, pythran/pythonic/include/numpy/ndarray/sort.hpp, pythran/pythonic/numpy/median.hpp, pythran/pythonic/numpy/ndarray/sort.hpp, pythran/pythonic/numpy/sort.hpp, pythran/tables.py, pythran/tests/test_numpy_func0.py, pythran/transformations/normalize_method_calls.py
Basically, forward `a.sort(kind='heapsort')` to `numpy.ndarray.sort`
while forwarding `a.sort(key=l)` to `list.sort` base don their signature.
As a side effect, and tot test that change, support `numpy.ndarray.sort` and
dispatching `sort` method calls to `list`, `ndarray` or `__dispatch__` when no
keyword is available.
Fix #1791
=> Handle static dispatching based on keyword signature

pythran/pythonic/include/scipy/special/binom.hpp, pythran/pythonic/scipy/special/binom.hpp, pythran/tables.py, pythran/tests/test_scipy.py, third_party/boost/math/special_functions/beta.hpp, third_party/boost/math/special_functions/binomial.hpp, third_party/boost/math/special_functions/detail/ibeta_inv_ab.hpp, third_party/boost/math/special_functions/detail/ibeta_inverse.hpp, third_party/boost/math/special_functions/detail/t_distribution_inv.hpp
That's the most common case, or at least the one needed for scipy.
The floating point case is not implemented in boost, giving up with it.
Fix #1804
=> Support scalar case of scipy.special.binom

pythran/pythonic/types/raw_array.hpp, pythran/tests/test_ndarray.py
That's not perfect because numpy actually raises a _ArrayMemoryError that
derives from MemoryError, but that's enough for our case.
=> Raise Memory Error upon (too) large numpy alloc

README.rst
Pythran got officially packaged today, along with beniget, since it is a build time dependency for scipy now
https://archlinux.org/packages/community/any/python-pythran/
=> Use pacman in ArchLinux

pythran/pythonic/numpy/bincount.hpp, pythran/tests/test_numpy_func2.py
I'm unsure if this is the correct fix (I don't think I properly understand the difference between begin and fbegin), however this fixes bincount if the weightsvector is a slice, which causes the error in #1819
=> Use iterator for index, fixes #1819

pythran/analyses/argument_effects.py, pythran/analyses/cfg.py, pythran/analyses/global_effects.py, pythran/graph.py, pythran/optimizations/forward_substitution.py, pythran/types/reorder.py, pythran/types/type_dependencies.py, pythran/typing.py, requirements.txt
Pythran only uses a small subset of networkx, and networkx brings a lot of
dependencies with it, including scipy, which implies a circular dependency when
using pythran to compile scipy.
As quoted by « someone on the internet » it's a good property for a compiler to
have minimal dependencies because it's used to build other stuff.
As a side effect also prune the dependency on decorator and six.
=> Move from networkx to a vendored solution

pythran/pythonic/python/core.hpp, pythran/tests/notebooks/export.ipynb
xref https://github.com/scipy/scipy/issues/14420. The `(reshaped)` bit has been confusing to me before.
=> Improve error message when input is a view (was `(reshaped)`)

pythran/magic.py, pythran/tests/__init__.py, pythran/tests/test_numpy_fft.py
When run with numpy-1.20, the use of `numpy.complex` emits a deprecation warning, recommending the use of Python `complex` instead
=> silence deprecation warnings

README.rst, docs/MANUAL.rst
Cf. [this announcement](https://www.freelists.org/post/pythran/Moving-the-IRC-chan-from-freenode-to-oftc) on the mailing list.
We also secure a few HTTP references in the process.
=> Change IRC reference from Freenode to OFTC

pythran/conversion.py
This is required to correctly compute the signature of numpy.mean, and should
unlock #1855
=> Basic support for to_eval of np._globals._NoValueType

pythran/pythonic/types/slice.hpp
This a really poor practice. Use the obvious check instead.
Fix #1870
=> Don't use signbit on integer

setup.py
According to upstream, pytest-runner is obsolete
Fix #1871
=> Remove pytest-runner references

pythran/analyses/immediates.py, pythran/pythonic/include/numpy/unique.hpp, pythran/pythonic/numpy/unique.hpp, pythran/tests/test_numpy_func3.py
https://github.com/serge-sans-paille/pythran/issues/1842#issuecomment-896320261
Hard code boolean arguments in numpy unique, at first, I only consider the case `len(node.args) >= 4` & `return_index` is true & `return_inverse` is true & `return_counts` is true.  
Next:
- [done]consider the case when `len(node.args) == 3` or `2` 
- [done] support `return_index` is true/false & `return_inverse` is true/false & `return_counts` is true/false.  
- use offset to generalize
=> Support  boolean arguments in numpy unique

pythran/analyses/immediates.py, pythran/intrinsic.py, pythran/tables.py
At first, I tried to use keywords name rather than offset:
```
for k, v in node.kwargs.items():
if k in alias.immediate_arguments:
if isinstance(v, ast.Constant):
self.result.add(v)     
```
but got the following error, saying no attribute `kwargs`, so I chose to use offset instead.
```
def visit_Call(self, node):
func_aliases = self.aliases[node.func]
for alias in func_aliases:
>           for k, v in node.kwargs.items():
E           AttributeError: 'Call' object has no attribute 'kwargs'
pythran/analyses/immediates.py:21: AttributeError
```
With my current offset implementation, I can pass the tests for `unique` in my local machine, but I can't pass tests for `mean` even on the master branch on my local machine:
```
------------------------------------------------ Captured stderr call …
```
=> General implementation of supporting immediate arguments

pythran/pythonic/include/numpy/mean.hpp, pythran/pythonic/include/numpy/unique.hpp, pythran/pythonic/include/types/immediate.hpp, pythran/pythonic/numpy/mean.hpp, pythran/pythonic/numpy/unique.hpp, pythran/tests/test_numpy_func0.py, pythran/tests/test_numpy_func3.py
This allows to pass keep_dims=1 even though a bool is expected.
=> Allow implicit conversion for immediate parameter

omp/__init__.py
This PR fixes three issues with libomp detection on macOS:
There may still be problems with other compilers but I only encountered issues with Apple Clang on macOS.
=> Better libomp detection on macOS

pythran/pythonic/builtins/assert.hpp, pythran/pythonic/include/builtins/assert.hpp
Otherwise the creation of the optional argument is not costless, which prevents
``assert cond`` to be a no-op under -DNDEBUG
=> Provide an extra assert overload without default argument

pythran/pythonic/include/numpy/floor_divide.hpp
Compilers are clever enough to generate branchless code for
(num >=0 && mun < 0) || (num < 0 && mun >= 0)
but not for
(num > 0 && mun < 0) || (num < 0 && mun > 0)
=> Faster check for opposite sign

pythran/pythonic/include/types/tuple.hpp, pythran/pythonic/types/numpy_gexpr.hpp
But with a different, static shape, which may trigger an irrelevant static
check. Replace the check by an assert.
=> Fix corner case when a numpy_gexpr is initialized from another gexpr

.gitignore, pythran/types/type_dependencies.py
Hi @serge-sans-paille 
I recognize that because you may not have access to a Windows Platform, you may find it cumbersome debugging the fix towards portable include paths.  For this reason I have **_attempted_** to complete the fix myself, since I use a Windows Platform.
So far it is working on my side.  But please take a look at the diffs to see if I did it correctly.
=> completed portability of include-paths

pythran/tables.py
Mark items(), keys() and values() as ConstMethod, as they don't change the dict
content.
Fix #1906
=> Update dict methods descriptor

docs/MANUAL.rst
=> Document how ``int`` type is implemented in pythran

pythran/cxxtypes.py
=> Limit the size of the callstack when dumping large expressions

pythran/pythonic/types/str.hpp
=> Do not mix rbegin and begin when initializing std::iterator

pythran/pythonic/include/types/numpy_texpr.hpp, pythran/pythonic/types/numpy_texpr.hpp
=> Provide minimal skeleton for vectorized texpr of broadcasted array

pythran/pythonic/include/types/str.hpp
A type must be default constructible to meet the forward iterator requirements.
GCC 12 won't compile `std::reverse_iterator<string_iterator>` without
this change.
=> Add default constructor to string_iterator

pythran/pythonic/types/variant_functor.hpp
This is not valid since C++20, see https://wg21.link/cwg2237
=> Remove template argument list from destructor name

pythran/analyses/global_declarations.py
This speeds up things a bit: no need to compute all use-def chains here.
=> Simplify global declaration processing

pythran/analyses/argument_effects.py, pythran/graph.py
intrinsic argument effect propagation is already taken care of in the
Call handler, there's no need to propagate this information back again.
Harder, Better, Faster, Stronger.
=> Avoid useless computations in argument_effects

pythran/toolchain.py
I was using Pythran and noticed this warning message, it seemed to me like this was intended to be "Nope..." instead of "Nop". Thanks!
=> Spelling typo nop -> nope

pythran/toolchain.py
This was removed from Python 3.11+, see https://github.com/python/cpython/issues/91670
=> Don't use removed sysconfig.get_config_vars()["SO"] in a doctest

pythran/tests/test_random.py
see deprecation notice in https://docs.python.org/3/library/random.html#random.shuffle
Fix #1995
=> Since python 3.11, random.shuffle takes a single argument

pythran/tests/test_numpy_func1.py, pythran/tests/test_numpy_func2.py
Fixes #2006 by skipping tests with the deprecated np.alen and np.asscalar
=> TEST: skip deprected np.alen, np.asscalar

pythran/tables.py
They are deprecated in Numpy.
Fix #2020
=> Drop support for numpy.bool, numpy.complex and numpy.float

pythran/pythonic/scipy/special/binom.hpp, pythran/pythonic/scipy/special/hankel1.hpp, pythran/pythonic/scipy/special/hankel2.hpp, pythran/pythonic/scipy/special/iv.hpp, pythran/pythonic/scipy/special/ivp.hpp, pythran/pythonic/scipy/special/jv.hpp, pythran/pythonic/scipy/special/jvp.hpp, pythran/pythonic/scipy/special/kv.hpp, pythran/pythonic/scipy/special/kvp.hpp, pythran/pythonic/scipy/special/spherical_jn.hpp, pythran/pythonic/scipy/special/spherical_yn.hpp, pythran/pythonic/scipy/special/yv.hpp, pythran/pythonic/scipy/special/yvp.hpp, pythran/pythonic/utils/boost_local_config.hpp, pythran/tests/test_scipy.py
Instead rely on boost to return the right NaN / inf value
This should fix https://github.com/scipy/scipy/pull/13957
=> Do not throw error for boost.special functions

pythran/pythonic/include/types/combined.hpp
When building scipy, one gets:
```
/usr/lib/python3.10/site-packages/pythran/pythonic/include/types/combined.hpp:304:17: error: ‘uint8_t’ was not declared in this scope
304 | SCALAR_COMBINER(uint8_t)
|                 ^~~~~~~
/usr/lib/python3.10/site-packages/pythran/pythonic/include/types/combined.hpp:300:21: note: in definition of macro ‘SCALAR_COMBINER’
300 |   struct __combined<Type, Type> {                                              \
|                     ^~~~
/usr/lib/python3.10/site-packages/pythran/pythonic/include/types/combined.hpp:5:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
4 | #include "pythonic/include/types/traits.hpp"
+++ |+#include <cstdint>
```
Bug: https://bugs.gentoo.org/878527
=> Fix build with GCC 13 (missing <cstdint> include)

pythran/pythonic/include/numpy/fft/fft.hpp, pythran/pythonic/numpy/fft/fft.hpp, pythran/pythonic/numpy/fft/fftn.hpp
Using small helpers to avoid spawning multiple definitions.
=> Cleanup numpy.fft.fft implementation

pythran/tables.py
__import__("a.b") != import a.b
Use importlib.import_module, as suggested by pydoc __import__
Fix #2041
=> Correctly import subpackage for introspection

pythran/pythonic/core.hpp, pythran/toolchain.py
Make sure Python's visibility macros are set before including any system headers, which are likely to include sys/features.h
My attempts to compile SciPy failed because `posix_memalign` was not declared.  This function is guarded by `_POSIX_C_SOURCE >= 200112`; my `pyconfig.h` defines `_POSIX_C_SOURCE = 200809`.  I think this is the simplest method to ensure Python's visibility macros are set before `sys/features.h` is included by a system header.
=> BUG: Include pyconfig.h first to define visibility macros

omp/__init__.py, pythran/config.py, pythran/dist.py, pythran/toolchain.py
It's deprecated, is easily broken by new setuptools releases, and will not be present at all for Python >= 3.12
Closes gh-2048
=> Only use `numpy.distutils` conditionally

pythran/analyses/range_values.py, pythran/tables.py, pythran/tests/test_optimizations.py
We should clean stack upon function's return to avoid variables cluttering each others.
Fix #2058
=> Fix range analysis in interprocedural context

pythran/conversion.py, pythran/pythonic/include/numpy/empty.hpp, pythran/pythonic/include/numpy/ndim.hpp, pythran/pythonic/include/numpy/ones.hpp, pythran/pythonic/include/numpy/size.hpp, pythran/pythonic/include/numpy/zeros.hpp, pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/include/types/tuple.hpp, pythran/pythonic/numpy/empty.hpp, pythran/pythonic/numpy/ndim.hpp, pythran/pythonic/numpy/ones.hpp, pythran/pythonic/numpy/zeros.hpp, pythran/pythonic/types/ndarray.hpp, pythran/tests/test_numpy_func0.py, pythran/tests/test_numpy_func2.py, third_party/xsimd/arch/xsimd_scalar.hpp
Have np.ones, empty and zeros return a scalar when invoked through an empty shape. Also make a few functions / accessors etc compatible with this model.
This is slightly different from numpy's implementation in that returns a "scalar array".
Fix #2071
=> Basic support of empty arrays

third_party/xsimd/arch/xsimd_scalar.hpp
This fixes xsimd on targets that don't use glibc.
Fix #2070
=> Backport 995ba19886255c84024afb5531154f314c840967 from xsimd

.github/workflows/parallel.yml, pythran/backend.py, pythran/tests/openmp.legacy/pythran_collapse.py
Because of the way looping works in python and C, we generally turn
for i in range(10):
...
into
for(int i = 0; i < 10; ++i)
...
if ( i != 10) i = 10
Don't do that if we can prove i is not escaping the loop's scope.
Fix #2064
=> Do not generate trailing loop update if not needed

pythran/optimizations/__init__.py, pythran/optimizations/copyto.py, pythran/pythonic/include/numpy/copyto.hpp, pythran/pythonic/include/types/list.hpp, pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/include/types/numpy_broadcast.hpp, pythran/pythonic/include/types/numpy_expr.hpp, pythran/pythonic/include/types/numpy_gexpr.hpp, pythran/pythonic/include/types/numpy_iexpr.hpp, pythran/pythonic/include/types/numpy_texpr.hpp, pythran/pythonic/include/types/numpy_vexpr.hpp, pythran/pythonic/include/types/tuple.hpp, pythran/pythonic/numpy/copyto.hpp, pythran/pythonic/types/list.hpp, pythran/pythonic/types/ndarray.hpp, pythran/pythonic/utils/broadcast_copy.hpp, pythran/pythran.cfg, pythran/tests/test_ndarray.py, pythran/tests/test_numpy_func3.py
Detect a[:] = expr pattern and use np.copyto(a, expr) instead. Use memcpy when possible (through broadcast_copy improvement). Accept moved reference.
=> Detect potential copyto usage and improve numpy.copyto support

pythran/pythonic/builtins/filter.hpp, pythran/pythonic/include/builtins/filter.hpp, pythran/pythonic/include/itertools/ifilter.hpp, pythran/pythonic/itertools/ifilter.hpp, pythran/tests/test_itertools.py
As a side effect, syndicate code between builtins.filter iterator and itertools.ifilter iterator, as they basically where the same (itertools.ifilter no longer exist in python3...)
=> Fix filtering of empty sequence

docs/CLI.rst, pythran/spec.py
=> Use pythran logger instead of default logger to report absence of spec

pythran/pythonic/types/complex.hpp
Hey 👋 !
These changes are necessary so that pythran continues to work with numpy complex types after numpy/numpy#24085 has been merged (this PR removes the complex structs that numpy has been using and replaces them with C99 native complex types, which do not have `.real` & `.imag` attributes) and numpy 2.0 has been released.
I'm not sure whether I should open a corresponding issue as well, so please let me know in case I need to do something more.
=> Use npy_creal/npy_cimag from npy_math in from_python::convert

pythran/optimizations/constant_folding.py, pythran/tables.py, pythran/tests/test_numpy_func2.py
It is not valid to consider it as 'read_once' as it behaves differently when taking a list or an iterator as input.
Fix #2135
=> Fix annotation of numpy.array

.github/workflows/core.yml, .github/workflows/icc.yml, .github/workflows/parallel.yml, .github/workflows/windows.yml
- Spread out jobs more across Python versions
- Update to the latest setup-python actions
- ~Run tests in `core.yml` on Ubuntu 22.04~
One other thing I considered but didn't do is to reduce the matrix in `core.yml` across Python versions and GCC/Clang. Now everything is double; it'd be much more efficient to test like:
- py37 : gcc
- py38 : clang
- py39: gcc
- etc.
Only PyPy is different enough that it should be tested with both GCC and Clang for the same PyPy interpreter version.
@serge-sans-paille happy to do that too if you want.
=> CI updates: add Python 3.11, and other minor maintenance

.github/workflows/core.yml, .github/workflows/doc.yml, .github/workflows/icc.yml, .github/workflows/parallel.yml, .github/workflows/windows.yml, docs/DEVGUIDE.rst, pythran/config.py, pythran/dist.py, pythran/tests/requirements.txt, pythran/tests/test_distutils.py, pythran/tests/test_distutils_numpy/setup.py, pythran/toolchain.py, requirements.txt
Since numpy 1.26.0, numpy.distutils is being removed in python 3.12, let's try to have a solution that work for 3.12 *and* previous version without numpy.distutils.
Fix #2148
=> Get rid of numpy.distutils

pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/include/types/numpy_gexpr.hpp, pythran/pythonic/include/types/numpy_iexpr.hpp, pythran/pythonic/include/types/numpy_texpr.hpp, pythran/pythonic/types/numpy_gexpr.hpp
Improve the simple runtime alias analysis to prevent some memory copies, based on the origin of each subexpression.
=> Avoid extra allocation when evaluation complex gexpr

pythran/pythonic/include/types/tuple.hpp
The order of the combination matters, and it wasn't respected.
Fix #2160
=> Fix tuple + indexable_container combiner

pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/python/core.hpp
This caused macro redefined warnings in SciPy when globally setting this macro on all build targets that have a numpy dependency.
=> Avoid redefining `NPY_NO_DEPRECATED_API` if already defined by user

pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/types/ndarray.hpp, pythran/tests/test_ndarray.py
But this creates a copy, I'm not very happy with this solution. Ideally we could avoid it.
Fix #2173
=> Allow taking the real/imag part of a numpy_iexpr

pythran/pythonic/include/numpy/argsort.hpp, pythran/pythonic/numpy/argsort.hpp, pythran/tests/test_numpy_func2.py
Reusing the infrastructure from numpy.ndarray.sort
Fix #2172
=> Support numpy.argsort kind keyword argument

pythran/pythonic/include/numpy/vectorize.hpp, pythran/pythonic/numpy/vectorize.hpp, pythran/tables.py, pythran/tests/test_numpy_func1.py
This all relies on existing logic around numpy_expr, so no big deal in terms of extra features to add.
This also paves the way for #2141  as we now "just" need to write a generic converted for `numpy::vectorized<F>`.
=> Add support for numpy.vectorize

pyproject.toml
Originally discovered by @rgommers 
Starting with #2162, building pythran with setuptools 60 or older results in failure to detect project name or version:
```
Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=2302 sha256=b46d11132f5384c143756b1ed741d7a1848b92f77ddc837eaebf68ad91ae333b
```
and setuptools 61 fails with:
```
ValueError: invalid pyproject.toml config: `tool.setuptools.dynamic`
```
Setuptools 62 or newer is required to build from source.
=> setuptools 62+ required to build

pyproject.toml, pythran/__init__.py, pythran/errors.py, pythran/run.py, pythran/tests/__init__.py, pythran/tests/test_cases.py, pythran/tests/test_openmp.py, pythran/toolchain.py
=> No longer rely on distutils for CompileError

pythran/config.py, pythran/dist.py, pythran/intrinsic.py, pythran/pythonic/include/operator_/imatmul.hpp, pythran/pythonic/numpy/vdot.hpp, pythran/pythonic/operator_/imatmul.hpp, pythran/tables.py, pythran/tests/test_advanced.py, pythran/tests/test_distutils/b.py, pythran/tests/test_distutils/setup.py, pythran/tests/test_ndarray.py, pythran/tests/test_numpy_fft.py
Based on the included headers, pythran now automatically removes the blas dependency.
Also do some cleanups (removing debug lines, some formatting, fix imatmul headers).
Fix #2203
=> Only link with blas when needed

.github/workflows/no-setuptools.yml, pythran/interval.py, pythran/pythonic/include/numpy/fix.hpp, pythran/pythonic/numpy/fix.hpp, pythran/tests/test_numpy_func0.py, pythran/toolchain.py
This should simplify the life of scipy maintainers, see #2228.
=> Remove dependency on setuptools for `pythran -E`

docs/MANUAL.rst, pythran/analyses/aliases.py, pythran/cxxtypes.py, pythran/pythonic/include/types/numpy_gexpr.hpp, pythran/tests/test_annotations.py, pythran/types/tog.py, pythran/types/type_dependencies.py, pythran/types/types.py
Pythran now understands type annotation attached to assignments. The type information takes precedence over the deduced type, which helps resolving issues with empty list / dict / set pythran previously had.
This patch does *not* add support for function return types, not does it changes anything in pythran decoration. Instead, it just adds support for local variable types.
Supported annotations are:
- bool / int / float / str
- tuple / list / set / dict
- plain ndarray (no view / transposed etc)
- numpy scalar types (int8, float32, complex128 etc)
It also supports deducing type from existing variables through `type(...)`, as in
a = foo(...)
b : list[type(a)] = []
which helps keeping the genericity of pythran code :-)
=> Add basic support for type annotation

pythran/config.py, pythran/pythonic/builtins/oct.hpp
It was only used once, as a legacy of Python 2 support (see 36d11d0d351d846b1a977746350f2d182ea21671 for the origin of the remaining piece of code). This should make #2257 easier too.
=> Remove any usage of __PYTHRAN__ macro

pythran/pythonic/include/numpy/array.hpp, pythran/tests/test_numpy_func2.py
=> Allow tuple with combinable items as array initializer

pythran/pythonic/include/numpy/float128.hpp, pythran/pythonic/include/types/ndarray.hpp, pythran/pythonic/numpy/float128.hpp, pythran/tests/test_numpy_func2.py
Related to #2275, but it's not enough to match scipy.signal.convolve performance.
=> Fix pythran support for numpy.float128

pythran/cxxgen.py
So that it also affects objects created at module loading time.
This seems to fix #2271
=> Move GIL manipulation right after module creation

.github/workflows/no-setuptools.yml, pythran/config.py
xref gh-2257. Putting this up for discussion early, with some comments. I considered adding `--config compiler.blas=none|openblas` support, but that then also has to interact with `--cflags` etc., so it's not clear that that works well for inclusion in 0.17.1 - and this can be added later.
The `--cflags-pythran-only` is the only thing we need for SciPy. It allows me to remove all this special handling:
https://github.com/scipy/scipy/blob/b98e79e4b326bf3beb4d861a744101ee7f438471/scipy/meson.build#L103-L138
and replace it with:
```meson
pythran_dep = []
if use_pythran
pythran_dep = dependency('pythran', version: '>=0.17.1')
endif
```
=> ENH: improvements to pythran-config for build system integration

.github/workflows/freethreading.yml
The changes in the fork were upstreamed and released in 5.5.0. See https://github.com/actions/setup-python/releases/tag/v5.5.0.
=> replace quansight-labs/setup-python with actions/setup-python

pythran/tests/test_named_parameters.py, pythran/transformations/remove_named_arguments.py
When the called function is a function parameter, the compiler used to break, it now walks all callers, verifies that call callers have compatible signatures and tries to handle the situation gracefully, or dies with a PythranSyntaxError
Fix #2313
=> Improve the normalization pass that removes keyword parameter
